<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 15 Introduction to R | DataManagement.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 15 Introduction to R | DataManagement.knit" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 Introduction to R | DataManagement.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="organizational-intelligence.html"/>
<link rel="next" href="data-visualization-1.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="data-management-databases-and-organizations.html"><a href="data-management-databases-and-organizations.html"><i class="fa fa-check"></i>Data Management: Databases and Organizations</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#supplements"><i class="fa fa-check"></i>Supplements</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="section-1-the-managerial-perspective.html"><a href="section-1-the-managerial-perspective.html"><i class="fa fa-check"></i>Section 1 The Managerial Perspective</a></li>
<li class="chapter" data-level="1" data-path="managing-data.html"><a href="managing-data.html"><i class="fa fa-check"></i><b>1</b> Managing Data</a>
<ul>
<li class="chapter" data-level="" data-path="managing-data.html"><a href="managing-data.html#learning-objectives"><i class="fa fa-check"></i>Learning objectives</a></li>
<li class="chapter" data-level="" data-path="managing-data.html"><a href="managing-data.html#introduction"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="managing-data.html"><a href="managing-data.html#individual-data-management"><i class="fa fa-check"></i>Individual data management</a></li>
<li class="chapter" data-level="" data-path="managing-data.html"><a href="managing-data.html#organizational-data-management"><i class="fa fa-check"></i>Organizational data management</a></li>
<li class="chapter" data-level="" data-path="managing-data.html"><a href="managing-data.html#problems-with-data-management-systems"><i class="fa fa-check"></i>Problems with data management systems</a></li>
<li class="chapter" data-level="" data-path="managing-data.html"><a href="managing-data.html#a-brief-history-of-data-management-systems"><i class="fa fa-check"></i>A brief history of data management systems</a></li>
<li class="chapter" data-level="" data-path="managing-data.html"><a href="managing-data.html#data-information-and-knowledge"><i class="fa fa-check"></i>Data, information, and knowledge</a></li>
<li class="chapter" data-level="" data-path="managing-data.html"><a href="managing-data.html#the-challenge"><i class="fa fa-check"></i>The challenge</a></li>
<li class="chapter" data-level="" data-path="managing-data.html"><a href="managing-data.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="information.html"><a href="information.html"><i class="fa fa-check"></i><b>2</b> Information</a>
<ul>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#learning-objectives-1"><i class="fa fa-check"></i>Learning objectives</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#introduction-1"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#a-historical-perspective"><i class="fa fa-check"></i>A historical perspective</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#a-brief-history-of-information-systems"><i class="fa fa-check"></i>A brief history of information systems</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#information-characteristics"><i class="fa fa-check"></i>Information characteristics</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#information-hardness"><i class="fa fa-check"></i>Information hardness</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#information-richness"><i class="fa fa-check"></i>Information richness</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#information-classes"><i class="fa fa-check"></i>Information classes</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#information-and-organizational-change"><i class="fa fa-check"></i>Information and organizational change</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#goal-setting-information"><i class="fa fa-check"></i>Goal-setting information</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#gap-information"><i class="fa fa-check"></i>Gap information</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#change-information"><i class="fa fa-check"></i>Change information</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#problem-solution"><i class="fa fa-check"></i>Problem solution</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#information-as-a-means-of-change"><i class="fa fa-check"></i>Information as a means of change</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#marketing"><i class="fa fa-check"></i>Marketing</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#customer-service"><i class="fa fa-check"></i>Customer Service</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#empowerment"><i class="fa fa-check"></i>Empowerment</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#information-and-managerial-work"><i class="fa fa-check"></i>Information and managerial work</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#managers-information-requirements"><i class="fa fa-check"></i>Managers’ information requirements</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#managers-needs-for-information-vary-accordingly-with-responsibilities"><i class="fa fa-check"></i>Managers’ needs for information vary accordingly with responsibilities</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#information-satisficing"><i class="fa fa-check"></i>Information satisficing</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#information-delivery-systems"><i class="fa fa-check"></i>Information delivery systems</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#information-integration"><i class="fa fa-check"></i>Information integration</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#knowledge-1"><i class="fa fa-check"></i>Knowledge</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#summary-1"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#references-and-additional-readings-1"><i class="fa fa-check"></i>References and additional readings</a></li>
<li class="chapter" data-level="" data-path="information.html"><a href="information.html#exercises-1"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="section-2-data-modeling-and-sql.html"><a href="section-2-data-modeling-and-sql.html"><i class="fa fa-check"></i>Section 2 Data Modeling and SQL</a></li>
<li class="chapter" data-level="3" data-path="the-single-entity.html"><a href="the-single-entity.html"><i class="fa fa-check"></i><b>3</b> The Single Entity</a>
<ul>
<li class="chapter" data-level="" data-path="the-single-entity.html"><a href="the-single-entity.html#the-relational-model"><i class="fa fa-check"></i>The relational model</a></li>
<li class="chapter" data-level="" data-path="the-single-entity.html"><a href="the-single-entity.html#getting-started"><i class="fa fa-check"></i>Getting started</a></li>
<li class="chapter" data-level="" data-path="the-single-entity.html"><a href="the-single-entity.html#modeling-a-single-entity-database"><i class="fa fa-check"></i>Modeling a single-entity database</a></li>
<li class="chapter" data-level="" data-path="the-single-entity.html"><a href="the-single-entity.html#creating-a-single-table-database"><i class="fa fa-check"></i>Creating a single-table database</a></li>
<li class="chapter" data-level="" data-path="the-single-entity.html"><a href="the-single-entity.html#summary-2"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="the-single-entity.html"><a href="the-single-entity.html#key-terms-and-concepts"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="the-single-entity.html"><a href="the-single-entity.html#exercises-2"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="the-one-to-many-relationship.html"><a href="the-one-to-many-relationship.html"><i class="fa fa-check"></i><b>4</b> The One-to-Many Relationship</a>
<ul>
<li class="chapter" data-level="" data-path="the-one-to-many-relationship.html"><a href="the-one-to-many-relationship.html#relationships"><i class="fa fa-check"></i>Relationships</a></li>
<li class="chapter" data-level="" data-path="the-one-to-many-relationship.html"><a href="the-one-to-many-relationship.html#creating-a-database-with-a-1m-relationship"><i class="fa fa-check"></i>Creating a database with a 1:m relationship</a></li>
<li class="chapter" data-level="" data-path="the-one-to-many-relationship.html"><a href="the-one-to-many-relationship.html#querying-a-two-table-database"><i class="fa fa-check"></i>Querying a two-table database</a></li>
<li class="chapter" data-level="" data-path="the-one-to-many-relationship.html"><a href="the-one-to-many-relationship.html#summary-3"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="the-one-to-many-relationship.html"><a href="the-one-to-many-relationship.html#key-terms-and-concepts-1"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="the-one-to-many-relationship.html"><a href="the-one-to-many-relationship.html#exercises-3"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="the-many-to-many-relationship.html"><a href="the-many-to-many-relationship.html"><i class="fa fa-check"></i><b>5</b> The Many-to-Many Relationship</a>
<ul>
<li class="chapter" data-level="" data-path="the-many-to-many-relationship.html"><a href="the-many-to-many-relationship.html#the-many-to-many-relationship-1"><i class="fa fa-check"></i>The many-to-many relationship</a></li>
<li class="chapter" data-level="" data-path="the-many-to-many-relationship.html"><a href="the-many-to-many-relationship.html#creating-a-relational-database-with-an-mm-relationship"><i class="fa fa-check"></i>Creating a relational database with an m:m relationship</a></li>
<li class="chapter" data-level="" data-path="the-many-to-many-relationship.html"><a href="the-many-to-many-relationship.html#querying-an-mm-relationship"><i class="fa fa-check"></i>Querying an m:m relationship</a></li>
<li class="chapter" data-level="" data-path="the-many-to-many-relationship.html"><a href="the-many-to-many-relationship.html#summary-4"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="the-many-to-many-relationship.html"><a href="the-many-to-many-relationship.html#key-terms-and-concepts-2"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="the-many-to-many-relationship.html"><a href="the-many-to-many-relationship.html#exercises-4"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html"><i class="fa fa-check"></i><b>6</b> One-to-One and Recursive Relationships</a>
<ul>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#learning-objectives-5"><i class="fa fa-check"></i>Learning objectives</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#modeling-a-one-to-one-relationship"><i class="fa fa-check"></i>Modeling a one-to-one relationship</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#mapping-a-one-to-one-relationship"><i class="fa fa-check"></i>Mapping a one-to-one relationship</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#mapping-a-recursive-one-to-many-relationship"><i class="fa fa-check"></i>Mapping a recursive one-to-many relationship</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#querying-a-one-to-one-relationship"><i class="fa fa-check"></i>Querying a one-to-one relationship</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#querying-a-recursive-1m-relationship"><i class="fa fa-check"></i>Querying a recursive 1:m relationship</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#modeling-a-recursive-one-to-one-relationship"><i class="fa fa-check"></i>Modeling a recursive one-to-one relationship</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#mapping-a-recursive-one-to-one-relationship"><i class="fa fa-check"></i>Mapping a recursive one-to-one relationship</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#querying-a-recursive-one-to-one-relationship"><i class="fa fa-check"></i>Querying a recursive one-to-one relationship</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#modeling-a-recursive-many-to-many-relationship"><i class="fa fa-check"></i>Modeling a recursive many-to-many relationship</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#mapping-a-recursive-many-to-many-relationship"><i class="fa fa-check"></i>Mapping a recursive many-to-many relationship</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#summary-5"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#key-terms-and-concepts-3"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="one-to-one-and-recursive-relationships.html"><a href="one-to-one-and-recursive-relationships.html#exercise"><i class="fa fa-check"></i>Exercise</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-modeling.html"><a href="data-modeling.html"><i class="fa fa-check"></i><b>7</b> Data Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#modeling"><i class="fa fa-check"></i>Modeling</a></li>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#data-modeling-1"><i class="fa fa-check"></i>Data modeling</a></li>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#the-building-blocks"><i class="fa fa-check"></i>The building blocks</a></li>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#data-model-quality"><i class="fa fa-check"></i>Data model quality</a></li>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#quality-improvement"><i class="fa fa-check"></i>Quality improvement</a></li>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#meaningful-identifiers"><i class="fa fa-check"></i>Meaningful identifiers</a></li>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#the-seven-habits-of-highly-effective-data-modelers"><i class="fa fa-check"></i>The seven habits of highly effective data modelers</a></li>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#summary-7"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#key-terms-and-concepts-4"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#references-and-additional-readings-2"><i class="fa fa-check"></i>References and additional readings</a></li>
<li class="chapter" data-level="" data-path="data-modeling.html"><a href="data-modeling.html#exercises-5"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reference-1-basic-structures.html"><a href="reference-1-basic-structures.html"><i class="fa fa-check"></i>Reference 1: Basic Structures</a>
<ul>
<li class="chapter" data-level="" data-path="reference-1-basic-structures.html"><a href="reference-1-basic-structures.html#one-entity"><i class="fa fa-check"></i>One entity</a></li>
<li class="chapter" data-level="" data-path="reference-1-basic-structures.html"><a href="reference-1-basic-structures.html#two-entities"><i class="fa fa-check"></i>Two entities</a></li>
<li class="chapter" data-level="" data-path="reference-1-basic-structures.html"><a href="reference-1-basic-structures.html#another-entitys-identifier-as-part-of-the-identifier"><i class="fa fa-check"></i>Another entity’s identifier as part of the identifier</a></li>
<li class="chapter" data-level="" data-path="reference-1-basic-structures.html"><a href="reference-1-basic-structures.html#exercises-6"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="normalization-and-other-data-modeling-methods.html"><a href="normalization-and-other-data-modeling-methods.html"><i class="fa fa-check"></i><b>8</b> Normalization and Other Data Modeling Methods</a>
<ul>
<li class="chapter" data-level="" data-path="normalization-and-other-data-modeling-methods.html"><a href="normalization-and-other-data-modeling-methods.html#normalization"><i class="fa fa-check"></i>Normalization</a></li>
<li class="chapter" data-level="" data-path="normalization-and-other-data-modeling-methods.html"><a href="normalization-and-other-data-modeling-methods.html#other-data-modeling-methods"><i class="fa fa-check"></i>Other data modeling methods</a></li>
<li class="chapter" data-level="" data-path="normalization-and-other-data-modeling-methods.html"><a href="normalization-and-other-data-modeling-methods.html#summary-8"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="normalization-and-other-data-modeling-methods.html"><a href="normalization-and-other-data-modeling-methods.html#key-terms-and-concepts-5"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="normalization-and-other-data-modeling-methods.html"><a href="normalization-and-other-data-modeling-methods.html#references-and-additional-readings-3"><i class="fa fa-check"></i>References and additional readings</a></li>
<li class="chapter" data-level="" data-path="normalization-and-other-data-modeling-methods.html"><a href="normalization-and-other-data-modeling-methods.html#exercises-7"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-relational-model-and-relational-algebra.html"><a href="the-relational-model-and-relational-algebra.html"><i class="fa fa-check"></i><b>9</b> The Relational Model and Relational Algebra</a>
<ul>
<li class="chapter" data-level="" data-path="the-relational-model-and-relational-algebra.html"><a href="the-relational-model-and-relational-algebra.html#data-structures"><i class="fa fa-check"></i>Data structures</a></li>
<li class="chapter" data-level="" data-path="the-relational-model-and-relational-algebra.html"><a href="the-relational-model-and-relational-algebra.html#integrity-rules"><i class="fa fa-check"></i>Integrity rules</a></li>
<li class="chapter" data-level="" data-path="the-relational-model-and-relational-algebra.html"><a href="the-relational-model-and-relational-algebra.html#manipulation-languages"><i class="fa fa-check"></i>Manipulation languages</a></li>
<li class="chapter" data-level="" data-path="the-relational-model-and-relational-algebra.html"><a href="the-relational-model-and-relational-algebra.html#a-primitive-set-of-relational-operators"><i class="fa fa-check"></i>A primitive set of relational operators</a></li>
<li class="chapter" data-level="" data-path="the-relational-model-and-relational-algebra.html"><a href="the-relational-model-and-relational-algebra.html#a-fully-relational-database"><i class="fa fa-check"></i>A fully relational database</a></li>
<li class="chapter" data-level="" data-path="the-relational-model-and-relational-algebra.html"><a href="the-relational-model-and-relational-algebra.html#summary-9"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="the-relational-model-and-relational-algebra.html"><a href="the-relational-model-and-relational-algebra.html#key-terms-and-concepts-6"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="the-relational-model-and-relational-algebra.html"><a href="the-relational-model-and-relational-algebra.html#references-and-additional-readings-4"><i class="fa fa-check"></i>References and additional readings</a></li>
<li class="chapter" data-level="" data-path="the-relational-model-and-relational-algebra.html"><a href="the-relational-model-and-relational-algebra.html#exercises-8"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="sql.html"><a href="sql.html"><i class="fa fa-check"></i><b>10</b> SQL</a>
<ul>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#introduction-3"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#data-definition"><i class="fa fa-check"></i>Data definition</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#keys"><i class="fa fa-check"></i>Keys</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#indexes"><i class="fa fa-check"></i>Indexes</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#notation"><i class="fa fa-check"></i>Notation</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#creating-a-table"><i class="fa fa-check"></i>Creating a table</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#constraints"><i class="fa fa-check"></i>Constraints</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#data-types"><i class="fa fa-check"></i>Data types</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#collation-sequence"><i class="fa fa-check"></i>Collation sequence</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#scalar-functions"><i class="fa fa-check"></i>Scalar functions</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#formatting"><i class="fa fa-check"></i>Formatting</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#altering-a-table"><i class="fa fa-check"></i>Altering a table</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#dropping-a-table"><i class="fa fa-check"></i>Dropping a table</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#creating-a-view"><i class="fa fa-check"></i>Creating a view</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#dropping-a-view"><i class="fa fa-check"></i>Dropping a view</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#creating-an-index"><i class="fa fa-check"></i>Creating an index</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#dropping-an-index"><i class="fa fa-check"></i>Dropping an index</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#data-manipulation"><i class="fa fa-check"></i>Data manipulation</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#qualifying-column-names"><i class="fa fa-check"></i>Qualifying column names</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#temporary-names"><i class="fa fa-check"></i>Temporary names</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#select"><i class="fa fa-check"></i>SELECT</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#insert"><i class="fa fa-check"></i>INSERT</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#update-1"><i class="fa fa-check"></i>UPDATE</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#delete-1"><i class="fa fa-check"></i>DELETE</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#sql-routines"><i class="fa fa-check"></i>SQL routines</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#sql-function"><i class="fa fa-check"></i>SQL function</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#sql-procedure"><i class="fa fa-check"></i>SQL procedure</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#trigger"><i class="fa fa-check"></i>Trigger</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#nullsmuch-ado-about-missing-information"><i class="fa fa-check"></i>Nulls—much ado about missing information</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#security"><i class="fa fa-check"></i>Security</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#grant"><i class="fa fa-check"></i>GRANT</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#revoke"><i class="fa fa-check"></i>REVOKE</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#the-system-catalog"><i class="fa fa-check"></i>The system catalog</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#natural-language-processing"><i class="fa fa-check"></i>Natural language processing</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#connectivity-and-odbc"><i class="fa fa-check"></i>Connectivity and ODBC</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#open-database-connectivity-odbc"><i class="fa fa-check"></i>Open database connectivity (ODBC)</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#embedded-sql"><i class="fa fa-check"></i>Embedded SQL</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#user-defined-types"><i class="fa fa-check"></i>User-defined types</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#the-future-of-sql"><i class="fa fa-check"></i>The future of SQL</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#summary-10"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#key-terms-and-concepts-7"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#references-and-additional-readings-5"><i class="fa fa-check"></i>References and additional readings</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#exercises-9"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reference-2-sql-playbook.html"><a href="reference-2-sql-playbook.html"><i class="fa fa-check"></i>Reference 2: SQL Playbook</a>
<ul>
<li class="chapter" data-level="" data-path="reference-2-sql-playbook.html"><a href="reference-2-sql-playbook.html#the-power-of-sql"><i class="fa fa-check"></i>The power of SQL</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="section-3-advanced-data-management.html"><a href="section-3-advanced-data-management.html"><i class="fa fa-check"></i>Section 3 Advanced Data Management</a></li>
<li class="chapter" data-level="11" data-path="spatial-and-temporal-data-management.html"><a href="spatial-and-temporal-data-management.html"><i class="fa fa-check"></i><b>11</b> Spatial and Temporal Data Management</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-and-temporal-data-management.html"><a href="spatial-and-temporal-data-management.html#learning-objectives-10"><i class="fa fa-check"></i>Learning objectives</a></li>
<li class="chapter" data-level="" data-path="spatial-and-temporal-data-management.html"><a href="spatial-and-temporal-data-management.html#introduction-4"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="spatial-and-temporal-data-management.html"><a href="spatial-and-temporal-data-management.html#managing-spatial-data"><i class="fa fa-check"></i>Managing spatial data</a></li>
<li class="chapter" data-level="" data-path="spatial-and-temporal-data-management.html"><a href="spatial-and-temporal-data-management.html#managing-temporal-data"><i class="fa fa-check"></i>Managing temporal data</a></li>
<li class="chapter" data-level="" data-path="spatial-and-temporal-data-management.html"><a href="spatial-and-temporal-data-management.html#summary-11"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="spatial-and-temporal-data-management.html"><a href="spatial-and-temporal-data-management.html#key-terms-and-concepts-8"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="spatial-and-temporal-data-management.html"><a href="spatial-and-temporal-data-management.html#references-and-additional-readings-6"><i class="fa fa-check"></i>References and additional readings</a></li>
<li class="chapter" data-level="" data-path="spatial-and-temporal-data-management.html"><a href="spatial-and-temporal-data-management.html#exercises-10"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="graph-databases.html"><a href="graph-databases.html"><i class="fa fa-check"></i><b>12</b> Graph Databases</a>
<ul>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#a-graph-database"><i class="fa fa-check"></i>A graph database</a></li>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#neo4j-a-graph-database-implementation"><i class="fa fa-check"></i>Neo4j – a graph database implementation</a></li>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#a-single-node"><i class="fa fa-check"></i>A single node</a></li>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#querying-a-node"><i class="fa fa-check"></i>Querying a node</a></li>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#a-relationship-between-nodes"><i class="fa fa-check"></i>A relationship between nodes</a></li>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#querying-an-mm-relationship-1"><i class="fa fa-check"></i>Querying an m:m relationship</a></li>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#recursive-relationships"><i class="fa fa-check"></i>Recursive relationships</a></li>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#summary-12"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#key-terms-and-concepts-9"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#references-and-additional-resources"><i class="fa fa-check"></i>References and additional resources</a></li>
<li class="chapter" data-level="" data-path="graph-databases.html"><a href="graph-databases.html#exercises-11"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="xml-managing-data-exchange.html"><a href="xml-managing-data-exchange.html"><i class="fa fa-check"></i><b>13</b> XML: Managing Data Exchange</a>
<ul>
<li class="chapter" data-level="" data-path="xml-managing-data-exchange.html"><a href="xml-managing-data-exchange.html#sgml"><i class="fa fa-check"></i>SGML</a></li>
<li class="chapter" data-level="" data-path="xml-managing-data-exchange.html"><a href="xml-managing-data-exchange.html#xml"><i class="fa fa-check"></i>XML</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="organizational-intelligence.html"><a href="organizational-intelligence.html"><i class="fa fa-check"></i><b>14</b> Organizational Intelligence</a>
<ul>
<li class="chapter" data-level="" data-path="organizational-intelligence.html"><a href="organizational-intelligence.html#the-data-warehouse"><i class="fa fa-check"></i>The data warehouse</a></li>
<li class="chapter" data-level="" data-path="organizational-intelligence.html"><a href="organizational-intelligence.html#exploiting-data-stores"><i class="fa fa-check"></i>Exploiting data stores</a></li>
<li class="chapter" data-level="" data-path="organizational-intelligence.html"><a href="organizational-intelligence.html#olap"><i class="fa fa-check"></i>OLAP</a></li>
<li class="chapter" data-level="" data-path="organizational-intelligence.html"><a href="organizational-intelligence.html#data-mining"><i class="fa fa-check"></i>Data mining</a></li>
<li class="chapter" data-level="" data-path="organizational-intelligence.html"><a href="organizational-intelligence.html#summary-14"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="organizational-intelligence.html"><a href="organizational-intelligence.html#key-terms-and-concepts-11"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="organizational-intelligence.html"><a href="organizational-intelligence.html#references-and-additional-readings-8"><i class="fa fa-check"></i>References and additional readings</a></li>
<li class="chapter" data-level="" data-path="organizational-intelligence.html"><a href="organizational-intelligence.html#exercises-13"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>15</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#the-r-project"><i class="fa fa-check"></i>The R project</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#database-access"><i class="fa fa-check"></i>Database access</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#timestamps"><i class="fa fa-check"></i>Timestamps</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#excel-files"><i class="fa fa-check"></i>Excel files</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#r-resources"><i class="fa fa-check"></i>R resources</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#r-and-data-analytics"><i class="fa fa-check"></i>R and data analytics</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#summary-15"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#key-terms-and-concepts-12"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#references"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#exercises-14"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="data-visualization-1.html"><a href="data-visualization-1.html"><i class="fa fa-check"></i><b>16</b> Data visualization</a>
<ul>
<li class="chapter" data-level="" data-path="data-visualization-1.html"><a href="data-visualization-1.html#visual-processing"><i class="fa fa-check"></i>Visual processing</a></li>
<li class="chapter" data-level="" data-path="data-visualization-1.html"><a href="data-visualization-1.html#the-grammar-of-graphics"><i class="fa fa-check"></i>The grammar of graphics</a></li>
<li class="chapter" data-level="" data-path="data-visualization-1.html"><a href="data-visualization-1.html#ggplot2"><i class="fa fa-check"></i>ggplot2</a></li>
<li class="chapter" data-level="" data-path="data-visualization-1.html"><a href="data-visualization-1.html#some-recipes"><i class="fa fa-check"></i>Some recipes</a></li>
<li class="chapter" data-level="" data-path="data-visualization-1.html"><a href="data-visualization-1.html#geographic-data"><i class="fa fa-check"></i>Geographic data</a></li>
<li class="chapter" data-level="" data-path="data-visualization-1.html"><a href="data-visualization-1.html#r-resources-1"><i class="fa fa-check"></i>R resources</a></li>
<li class="chapter" data-level="" data-path="data-visualization-1.html"><a href="data-visualization-1.html#summary-16"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="data-visualization-1.html"><a href="data-visualization-1.html#references-1"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="" data-path="data-visualization-1.html"><a href="data-visualization-1.html#exercises-15"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html"><i class="fa fa-check"></i><b>17</b> Text mining &amp; natural language processing</a>
<ul>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#the-nature-of-language"><i class="fa fa-check"></i>The nature of language</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#levels-of-processing"><i class="fa fa-check"></i>Levels of processing</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#tokenization"><i class="fa fa-check"></i>Tokenization</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#sentiment-analysis"><i class="fa fa-check"></i>Sentiment analysis</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#corpus"><i class="fa fa-check"></i>Corpus</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#readability"><i class="fa fa-check"></i>Readability</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#preprocessing"><i class="fa fa-check"></i>Preprocessing</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#word-frequency-analysis"><i class="fa fa-check"></i>Word frequency analysis</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#co-occurrence-and-association"><i class="fa fa-check"></i>Co-occurrence and association</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#cluster-analysis"><i class="fa fa-check"></i>Cluster analysis</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#topic-modeling"><i class="fa fa-check"></i>Topic modeling</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#named-entity-recognition-ner"><i class="fa fa-check"></i>Named-entity recognition (NER)</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#future-developments"><i class="fa fa-check"></i>Future developments</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#summary-17"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#key-terms-and-concepts-13"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#references-2"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="" data-path="text-mining-natural-language-processing.html"><a href="text-mining-natural-language-processing.html#exercises-16"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="cluster-computing.html"><a href="cluster-computing.html"><i class="fa fa-check"></i><b>18</b> Cluster computing</a>
<ul>
<li class="chapter" data-level="" data-path="cluster-computing.html"><a href="cluster-computing.html#a-paradigm-shift"><i class="fa fa-check"></i>A paradigm shift</a></li>
<li class="chapter" data-level="" data-path="cluster-computing.html"><a href="cluster-computing.html#the-drivers"><i class="fa fa-check"></i>The drivers</a></li>
<li class="chapter" data-level="" data-path="cluster-computing.html"><a href="cluster-computing.html#the-bottleneck-and-its-solution"><i class="fa fa-check"></i>The bottleneck and its solution</a></li>
<li class="chapter" data-level="" data-path="cluster-computing.html"><a href="cluster-computing.html#lambda-architecture"><i class="fa fa-check"></i>Lambda Architecture</a></li>
<li class="chapter" data-level="" data-path="cluster-computing.html"><a href="cluster-computing.html#hadoop"><i class="fa fa-check"></i>Hadoop</a></li>
<li class="chapter" data-level="" data-path="cluster-computing.html"><a href="cluster-computing.html#spark"><i class="fa fa-check"></i>Spark</a></li>
<li class="chapter" data-level="" data-path="cluster-computing.html"><a href="cluster-computing.html#summary-18"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="dashboards.html"><a href="dashboards.html"><i class="fa fa-check"></i><b>19</b> Dashboards</a>
<ul>
<li class="chapter" data-level="" data-path="dashboards.html"><a href="dashboards.html#the-value-of-dashboards"><i class="fa fa-check"></i>The value of dashboards</a></li>
<li class="chapter" data-level="" data-path="dashboards.html"><a href="dashboards.html#summary-19"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="section-4-managing-organizational-memory.html"><a href="section-4-managing-organizational-memory.html"><i class="fa fa-check"></i>Section 4 Managing Organizational Memory</a></li>
<li class="chapter" data-level="20" data-path="data-structure-and-storage.html"><a href="data-structure-and-storage.html"><i class="fa fa-check"></i><b>20</b> Data Structure and Storage</a>
<ul>
<li class="chapter" data-level="" data-path="data-structure-and-storage.html"><a href="data-structure-and-storage.html#the-data-deluge"><i class="fa fa-check"></i>The data deluge</a></li>
<li class="chapter" data-level="" data-path="data-structure-and-storage.html"><a href="data-structure-and-storage.html#data-structures-1"><i class="fa fa-check"></i>Data structures</a></li>
<li class="chapter" data-level="" data-path="data-structure-and-storage.html"><a href="data-structure-and-storage.html#data-coding-standards"><i class="fa fa-check"></i>Data coding standards</a></li>
<li class="chapter" data-level="" data-path="data-structure-and-storage.html"><a href="data-structure-and-storage.html#data-storage-devices"><i class="fa fa-check"></i>Data storage devices</a></li>
<li class="chapter" data-level="" data-path="data-structure-and-storage.html"><a href="data-structure-and-storage.html#data-compression"><i class="fa fa-check"></i>Data compression</a></li>
<li class="chapter" data-level="" data-path="data-structure-and-storage.html"><a href="data-structure-and-storage.html#summary-20"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="data-structure-and-storage.html"><a href="data-structure-and-storage.html#key-terms-and-concepts-15"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="data-structure-and-storage.html"><a href="data-structure-and-storage.html#exercises-19"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html"><i class="fa fa-check"></i><b>21</b> Data Processing Architectures</a>
<ul>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#architectural-choices"><i class="fa fa-check"></i>Architectural choices</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#remote-job-entry"><i class="fa fa-check"></i>Remote job entry</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#personal-database"><i class="fa fa-check"></i>Personal database</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#clientserver"><i class="fa fa-check"></i>Client/server</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#cloud-computing"><i class="fa fa-check"></i>Cloud computing</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#distributed-database"><i class="fa fa-check"></i>Distributed database</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#distributed-data-access"><i class="fa fa-check"></i>Distributed data access</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#distributed-database-design"><i class="fa fa-check"></i>Distributed database design</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#summary-21"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#key-terms-and-concepts-16"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#references-and-additional-readings-10"><i class="fa fa-check"></i>References and additional readings</a></li>
<li class="chapter" data-level="" data-path="data-processing-architectures.html"><a href="data-processing-architectures.html#exercises-20"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="sql-and-java.html"><a href="sql-and-java.html"><i class="fa fa-check"></i><b>22</b> SQL and Java</a>
<ul>
<li class="chapter" data-level="" data-path="sql-and-java.html"><a href="sql-and-java.html#jdbc"><i class="fa fa-check"></i>JDBC</a></li>
<li class="chapter" data-level="" data-path="sql-and-java.html"><a href="sql-and-java.html#java-ee"><i class="fa fa-check"></i>Java EE</a></li>
<li class="chapter" data-level="" data-path="sql-and-java.html"><a href="sql-and-java.html#using-sql-within-java"><i class="fa fa-check"></i>Using SQL within Java</a></li>
<li class="chapter" data-level="" data-path="sql-and-java.html"><a href="sql-and-java.html#javaserver-pages-jsp"><i class="fa fa-check"></i>JavaServer Pages (JSP)</a></li>
<li class="chapter" data-level="" data-path="sql-and-java.html"><a href="sql-and-java.html#summary-22"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="sql-and-java.html"><a href="sql-and-java.html#key-terms-and-concepts-17"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="sql-and-java.html"><a href="sql-and-java.html#references-and-additional-readings-11"><i class="fa fa-check"></i>References and additional readings</a></li>
<li class="chapter" data-level="" data-path="sql-and-java.html"><a href="sql-and-java.html#exercises-21"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="data-integrity.html"><a href="data-integrity.html"><i class="fa fa-check"></i><b>23</b> Data Integrity</a>
<ul>
<li class="chapter" data-level="" data-path="data-integrity.html"><a href="data-integrity.html#introduction-9"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="data-integrity.html"><a href="data-integrity.html#transaction-management"><i class="fa fa-check"></i>Transaction management</a></li>
<li class="chapter" data-level="" data-path="data-integrity.html"><a href="data-integrity.html#protecting-existence"><i class="fa fa-check"></i>Protecting existence</a></li>
<li class="chapter" data-level="" data-path="data-integrity.html"><a href="data-integrity.html#maintaining-data-quality"><i class="fa fa-check"></i>Maintaining data quality</a></li>
<li class="chapter" data-level="" data-path="data-integrity.html"><a href="data-integrity.html#ensuring-confidentiality"><i class="fa fa-check"></i>Ensuring confidentiality</a></li>
<li class="chapter" data-level="" data-path="data-integrity.html"><a href="data-integrity.html#summary-23"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="data-integrity.html"><a href="data-integrity.html#key-terms-and-concepts-18"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="data-integrity.html"><a href="data-integrity.html#exercises-22"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="data-administration.html"><a href="data-administration.html"><i class="fa fa-check"></i><b>24</b> Data Administration</a>
<ul>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#introduction-10"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#the-chief-data-officer"><i class="fa fa-check"></i>The Chief Data Officer</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#management-of-the-database-environment"><i class="fa fa-check"></i>Management of the database environment</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#data-administration-1"><i class="fa fa-check"></i>Data administration</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#database-management-systems-dbmss"><i class="fa fa-check"></i>Database management systems (DBMSs)</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#groupware-1"><i class="fa fa-check"></i>Groupware</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#data-integration"><i class="fa fa-check"></i>Data integration</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#conclusion-9"><i class="fa fa-check"></i>Conclusion</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#summary-24"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#key-terms-and-concepts-19"><i class="fa fa-check"></i>Key terms and concepts</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#references-and-additional-readings-12"><i class="fa fa-check"></i>References and additional readings</a></li>
<li class="chapter" data-level="" data-path="data-administration.html"><a href="data-administration.html#exercises-23"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-r" class="section level1" number="15">
<h1><span class="header-section-number">Chapter 15</span> Introduction to R</h1>
<blockquote>
<p><em>Statistics are no substitute for judgment</em></p>
<p>Henry Clay, U.S. congressman and senator</p>
</blockquote>
<div id="learning-objectives-14" class="section level3 unnumbered">
<h3>Learning objectives</h3>
<p>Students completing this chapter will:</p>
<ul>
<li><p>Be able to use R for file handling and basic statistics;</p></li>
<li><p>Be competent in the use of RStudio.</p></li>
</ul>
</div>
<div id="the-r-project" class="section level2 unnumbered">
<h2>The R project</h2>
<p>The <a href="http://www.r-project.org"><u>R project</u></a> supports ongoing
development of R, a free software environment for statistical computing,
data visualization, and data analytics. It is a highly-extensible
platform, the R programming language is object-oriented, and R runs on
the common operating systems. There is evidence to indicate that
adoption of R has grown in recent years, and is now the one of the most
popular analytics platform.</p>
<p><a href="http://www.rstudio.com"><u>RStudio</u></a> is a commonly used integrated
development environment (IDE) for R. It contains four windows. The
upper-left window contains scripts, one or more lines of R code that
constitute a task. Scripts can be saved and reused. It is good practice
to save scripts as you will find you can often edit an existing script
to meet the needs of a new task. The upper-right window provides details
of all datasets created. It also useful for importing datasets and
reviewing the history of R commands executed. The lower-left window
displays the results of executed scripts. If you want to clear this
window, then press control-L. The lower-right window can be used to show
files on your system, plots you have created by executing a script,
packages installed and loaded, and help information.</p>
<div id="creating-a-project" class="section level3 unnumbered">
<h3>Creating a project</h3>
<p>It usually makes sense to store all R scripts and data in the same
folder or directory. Thus, when you first start RStudio, create a new
project.</p>
<p>Project &gt; Create Project…</p>
<p>RStudio remembers the state of each window, so when you quit and reopen,
it will restore the windows to their prior state. You can also open an
existing project, which sets the path to the folder for that project. As
a result, all saved scripts and files during a session are stored in
that folder.</p>
<p><em>RStudio interface</em></p>
<p><img src="Figures/Section%202/RStudio.png" /></p>
</div>
<div id="scripting" class="section level3 unnumbered">
<h3>Scripting</h3>
<p>A script is a set of R commands. You can also think of it as a short
program.</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="introduction-to-r.html#cb293-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CO2 parts per million (ppm) for 2000-2009</span></span>
<span id="cb293-2"><a href="introduction-to-r.html#cb293-2" aria-hidden="true" tabindex="-1"></a>co2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">369.40</span>,<span class="fl">371.07</span>,<span class="fl">373.17</span>,<span class="fl">375.78</span>,<span class="fl">377.52</span>,<span class="fl">379.76</span>,<span class="fl">381.85</span>,<span class="fl">383.71</span>,<span class="fl">385.57</span>,<span class="fl">384.78</span>)</span>
<span id="cb293-3"><a href="introduction-to-r.html#cb293-3" aria-hidden="true" tabindex="-1"></a>year <span class="ot">&lt;-</span>  (<span class="dv">2000</span><span class="sc">:</span><span class="dv">2009</span>) <span class="co"># a range of values</span></span>
<span id="cb293-4"><a href="introduction-to-r.html#cb293-4" aria-hidden="true" tabindex="-1"></a><span class="co"># show values</span></span>
<span id="cb293-5"><a href="introduction-to-r.html#cb293-5" aria-hidden="true" tabindex="-1"></a>co2</span></code></pre></div>
<pre><code>##  [1] 369.40 371.07 373.17 375.78 377.52 379.76 381.85 383.71 385.57 384.78</code></pre>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="introduction-to-r.html#cb295-1" aria-hidden="true" tabindex="-1"></a>year</span></code></pre></div>
<pre><code>##  [1] 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009</code></pre>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="introduction-to-r.html#cb297-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute mean and standard deviation</span></span>
<span id="cb297-2"><a href="introduction-to-r.html#cb297-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(co2)</span></code></pre></div>
<pre><code>## [1] 378.261</code></pre>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="introduction-to-r.html#cb299-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(co2)</span></code></pre></div>
<pre><code>## [1] 5.807934</code></pre>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="introduction-to-r.html#cb301-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(year,co2)</span></code></pre></div>
<p><img src="DataManagement_files/figure-html/sample-script-1.png" width="672" /></p>
<p>The previous script</p>
<ul>
<li><p>Creates an object co2 with the values 369.40, 371.07, … , 348.78.</p></li>
<li><p>Creates an object year with values 2000 through 2009.</p></li>
<li><p>Displays in the lower-left window the values stored in these two
objects.</p></li>
<li><p>Computes the mean for each variable.</p></li>
<li><p>Creates an x-y plot of year and co2, which is shown in the
lower-right window.</p></li>
</ul>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td>Note the use of &lt;- for assigning values to an object and that c is
short for combine in the expression:<a href="#fn39" class="footnote-ref" id="fnref39"><sup>39</sup></a></td>
</tr>
</tbody>
</table>
<table style="width:94%;">
<colgroup>
<col width="94%" />
</colgroup>
<tbody>
<tr class="odd">
<td><h3 id="smart-editing">Smart editing</h3>
<p>It is not uncommon to find that a dataset you would like to use
is in electronic format, but not in a format that matches your
need. In most cases, you can use a word processor, spreadsheet,
or text editor to reformat the data. In the case of the data in
the previous table, here is a recipe for reformatting the data.</p>
<ol style="list-style-type: decimal">
<li><p>Copy each column to a word processor</p></li>
<li><p>Use the convert table to text command</p></li>
<li><p>Search and replace commas with nulls (i.e, ““)</p></li>
<li><p>Search and replace returns with commas</p></li>
<li><p>Edit to put R code around numbers</p></li>
</ol>
<p>In some cases, you might find it quicker to copy a table to a
spreadsheet, select each column within the spreadsheet, and then
proceed as described above. This technique works well when the
original table is in a pdf document.</p></td>
</tr>
</tbody>
</table>
<blockquote>
<p>❓<strong>Skill builder</strong></p>
<p>Plot kWh per square foot by year for the following University of
Georgia data.</p>
<table>
<thead>
<tr class="header">
<th align="left">year</th>
<th align="left">square feet</th>
<th align="left">kWh</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2007</td>
<td align="left">14,214,216</td>
<td align="left">2,141,705</td>
</tr>
<tr class="even">
<td align="left">2008</td>
<td align="left">14,359,041</td>
<td align="left">2,108,088</td>
</tr>
<tr class="odd">
<td align="left">2009</td>
<td align="left">14,752,886</td>
<td align="left">2,150,841</td>
</tr>
<tr class="even">
<td align="left">2010</td>
<td align="left">15,341,886</td>
<td align="left">2,211,414</td>
</tr>
<tr class="odd">
<td align="left">2011</td>
<td align="left">15,573,100</td>
<td align="left">2,187,164</td>
</tr>
<tr class="even">
<td align="left">2012</td>
<td align="left">15,740,742</td>
<td align="left">2,057,364</td>
</tr>
</tbody>
</table>
<h1 id="data-in-r-format">Data in R format</h1>
<p>year &lt;- (2007:2012)</p>
<p>sqft &lt;- c(14214216, 14359041, 14752886, 15341886, 15573100, 15740742)</p>
<p>kwh &lt;- c(2141705, 2108088, 2150841, 2211414, 2187164, 2057364)</p>
</blockquote>
</div>
<div id="datasets" class="section level3 unnumbered">
<h3>Datasets</h3>
<p>An R dataset is the familiar table of the relational model. There is one
row for each observation, and the columns contain the observed values or
facts about each observation. R supports multiple data structures and
data types.</p>
<div id="vector" class="section level4 unnumbered">
<h4>Vector</h4>
<p>A vector is a single row table where data are all of the same type
(e.g., character, logical, numeric). In the following sample code, two
numeric vectors are created.</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="introduction-to-r.html#cb302-1" aria-hidden="true" tabindex="-1"></a>co2 <span class="ot">&lt;-</span>  <span class="fu">c</span>(<span class="fl">369.40</span>,<span class="fl">371.07</span>,<span class="fl">373.17</span>,<span class="fl">375.78</span>,<span class="fl">377.52</span>,<span class="fl">379.76</span>,<span class="fl">381.85</span>,<span class="fl">383.71</span>,<span class="fl">385.57</span>,<span class="fl">384.78</span>)</span>
<span id="cb302-2"><a href="introduction-to-r.html#cb302-2" aria-hidden="true" tabindex="-1"></a>year <span class="ot">&lt;-</span>  (<span class="dv">2000</span><span class="sc">:</span><span class="dv">2009</span>)</span>
<span id="cb302-3"><a href="introduction-to-r.html#cb302-3" aria-hidden="true" tabindex="-1"></a>co2[<span class="dv">2</span>] <span class="co"># show the second value</span></span></code></pre></div>
<pre><code>## [1] 371.07</code></pre>
</div>
<div id="matrix" class="section level4 unnumbered">
<h4>Matrix</h4>
<p>A matrix is a table where all data are of the same type. Because it is a
table, a matrix has two dimensions, which need to be specified when
defining the matrix. The sample code creates a matrix with 4 rows and 3
columns, as the results of the executed code illustrate.</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="introduction-to-r.html#cb304-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">nrow=</span><span class="dv">4</span>,<span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb304-2"><a href="introduction-to-r.html#cb304-2" aria-hidden="true" tabindex="-1"></a>m[<span class="dv">4</span>,<span class="dv">3</span>] <span class="co"># show the value in row 4, column 3</span></span></code></pre></div>
<pre><code>## [1] 12</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th>[,1]</th>
<th>[,2]</th>
<th>[,3]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>[1,]</td>
<td>1</td>
<td>5</td>
<td>9</td>
</tr>
<tr class="even">
<td>[2,]</td>
<td>2</td>
<td>6</td>
<td>10</td>
</tr>
<tr class="odd">
<td>[3,]</td>
<td>3</td>
<td>7</td>
<td>11</td>
</tr>
<tr class="even">
<td>[4,]</td>
<td>4</td>
<td>8</td>
<td>12</td>
</tr>
</tbody>
</table>
<blockquote>
<p>❓<strong>Skill builder</strong> Create a matrix with 6 rows and 3 columns
containing the numbers 1 through 18.</p>
</blockquote>
</div>
<div id="array" class="section level4 unnumbered">
<h4>Array</h4>
<p>An array is a multidimensional table. It extends a matrix beyond two
dimensions. Review the results of running the following code by
displaying the array created.</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="introduction-to-r.html#cb306-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span>  <span class="fu">array</span>(letters[<span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">24</span>)], <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">2</span>))</span>
<span id="cb306-2"><a href="introduction-to-r.html#cb306-2" aria-hidden="true" tabindex="-1"></a>a[<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>] <span class="co"># show the first value in the array</span></span></code></pre></div>
<pre><code>## [1] &quot;a&quot;</code></pre>
</div>
<div id="data-frame" class="section level4 unnumbered">
<h4>Data frame</h4>
<p>While vectors, matrices, and arrays are all forms of a table, they are
restricted to data of the same type (e.g., numeric). A data frame, like
a relational table, can have columns of different data types. The sample
code creates a data frame with character and numeric data types.</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="introduction-to-r.html#cb308-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;m&quot;</span>,<span class="st">&quot;f&quot;</span>,<span class="st">&quot;f&quot;</span>)</span>
<span id="cb308-2"><a href="introduction-to-r.html#cb308-2" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">8</span>,<span class="dv">3</span>)</span>
<span id="cb308-3"><a href="introduction-to-r.html#cb308-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span>  <span class="fu">data.frame</span>(gender,age)</span>
<span id="cb308-4"><a href="introduction-to-r.html#cb308-4" aria-hidden="true" tabindex="-1"></a><span class="co"># show some data frame values</span></span>
<span id="cb308-5"><a href="introduction-to-r.html#cb308-5" aria-hidden="true" tabindex="-1"></a>df[<span class="dv">1</span>,<span class="dv">2</span>] <span class="co"># a cell</span></span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="introduction-to-r.html#cb310-1" aria-hidden="true" tabindex="-1"></a>df[<span class="dv">1</span>,] <span class="co"># a row</span></span></code></pre></div>
<pre><code>##   gender age
## 1      m   5</code></pre>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="introduction-to-r.html#cb312-1" aria-hidden="true" tabindex="-1"></a>df[,<span class="dv">2</span>] <span class="co"># a column</span></span></code></pre></div>
<pre><code>## [1] 5 8 3</code></pre>
</div>
<div id="list" class="section level4 unnumbered">
<h4>List</h4>
<p>The most general form of data storage is a list, which is an ordered
collection of objects. It permits you to store a variety of objects
together under a single name. In other words, a list is an object that
contains other objects. Retrieve a list member with a <em>single square
bracket</em> []. To reference a list member directly, use a <em>double square
bracket</em> [[]].</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="introduction-to-r.html#cb314-1" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span>  <span class="fu">list</span>(co2,m,df)</span>
<span id="cb314-2"><a href="introduction-to-r.html#cb314-2" aria-hidden="true" tabindex="-1"></a><span class="co"># show a list member</span></span>
<span id="cb314-3"><a href="introduction-to-r.html#cb314-3" aria-hidden="true" tabindex="-1"></a>l[<span class="dv">3</span>] <span class="co"># retrieves list member</span></span></code></pre></div>
<pre><code>## [[1]]
##   gender age
## 1      m   5
## 2      f   8
## 3      f   3</code></pre>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="introduction-to-r.html#cb316-1" aria-hidden="true" tabindex="-1"></a>l[[<span class="dv">3</span>]] <span class="co"># reference a list member</span></span></code></pre></div>
<pre><code>##   gender age
## 1      m   5
## 2      f   8
## 3      f   3</code></pre>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="introduction-to-r.html#cb318-1" aria-hidden="true" tabindex="-1"></a>l[[<span class="dv">1</span>]][<span class="dv">2</span>] <span class="co"># second element of list 1</span></span></code></pre></div>
<pre><code>## [1] 371.07</code></pre>
</div>
</div>
<div id="logical-operators" class="section level3 unnumbered">
<h3>Logical operators</h3>
<p>R supports the common logical operators, as shown in the following
table.</p>
<table>
<thead>
<tr class="header">
<th align="left">Logical operator</th>
<th align="left">Symbol</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">EQUAL</td>
<td align="left">==’</td>
</tr>
<tr class="even">
<td align="left">AND</td>
<td align="left">&amp;</td>
</tr>
<tr class="odd">
<td align="left">OR</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">NOT</td>
<td align="left">!</td>
</tr>
</tbody>
</table>
<div id="object" class="section level4 unnumbered">
<h4>Object</h4>
<p>In R, an object is anything that can be assigned to a variable. It can
be a constant, a function, a data structure, a graph, a times series,
and so on. You find that the various packages in R support the creation
of a wide range of objects and provide functions to work with these and
other objects. A variable is a way of referring to an object. Thus, we
might use the variable named <em>l</em> to refer to the list object defined in
the preceding subsection.</p>
</div>
</div>
<div id="types-of-data" class="section level3 unnumbered">
<h3>Types of data</h3>
<p>R can handle the four types of data: nominal, ordinal, interval, and
ratio. Nominal data, typically character strings, are used for
classification (e.g., high, medium, or low). Ordinal data represent an
ordering and thus can be sorted (e.g., the seeding or ranking of players
for a tennis tournament). The intervals between ordinal data are not
necessarily equal. Thus, the top seeded tennis play (ranked 1) might be
far superior to the second seeded (ranked 2), who might be only
marginally better than the third seed (ranked 3). Interval and ratio are
forms of measurement data. The interval between the units of measure for
interval data are equal. In other words, the distance between 50cm and
51cm is the same as the distance between 105cm and 106cm. Ratio data
have equal intervals and a natural zero point. Time, distance, and mass
are examples of ratio scales. Celsius and Fahrenheit are interval data
types, but not ratio, because the zero point is arbitrary. As a result,
10º C is not twice as hot as 5º C. Whereas, Kelvin is a ratio data type
because nothing can be colder than 0º K, a natural zero point.</p>
<p>In R, nominal and ordinal data types are also known as <em>factors</em>.
Defining a column as a factor determines how its data are analyzed and
presented. By default, factor levels for character vectors are created
in alphabetical order, which is often not what is desired. To be
precise, specify using the levels option.</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="introduction-to-r.html#cb320-1" aria-hidden="true" tabindex="-1"></a>rating <span class="ot">&lt;-</span>   <span class="fu">c</span>(<span class="st">&#39;high&#39;</span>,<span class="st">&#39;medium&#39;</span>,<span class="st">&#39;low&#39;</span>)</span>
<span id="cb320-2"><a href="introduction-to-r.html#cb320-2" aria-hidden="true" tabindex="-1"></a>rating <span class="ot">&lt;-</span>  <span class="fu">factor</span>(rating, <span class="at">order=</span>T, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&#39;high&#39;</span>,<span class="st">&#39;medium&#39;</span>,<span class="st">&#39;low&#39;</span>))</span></code></pre></div>
<p>Thus, the preceding code will result in changing the default reporting
of factors from alphabetical order (i.e., high, low, and medium) to
listing them in the specified order (i.e., high, medium, and low).</p>
</div>
<div id="missing-values" class="section level3 unnumbered">
<h3>Missing values</h3>
<p>Missing values in R are represented as NA, meaning not available.
Infeasible values, such as the result of dividing by zero, are indicated
by NaN, meaning not a number. Any arithmetic expression or function
operating on data containing missing values will return NA. Thus
<code>sum(c(1,NA,2))</code> will return NA.</p>
<p>To exclude missing values from calculations, use the option <code>na.rm = T</code>,
which specifies the removal of missing values prior to calculations.
Thus, <code>sum(c(1,NA,2),na.rm=T)</code> will return 3.</p>
<p>You can remove rows with missing data by using <code>na.omit()</code>, which will
delete those rows containing missing values.</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="introduction-to-r.html#cb321-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;m&quot;</span>,<span class="st">&quot;f&quot;</span>,<span class="st">&quot;f&quot;</span>,<span class="st">&quot;f&quot;</span>)</span>
<span id="cb321-2"><a href="introduction-to-r.html#cb321-2" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">8</span>,<span class="dv">3</span>,<span class="cn">NA</span>)</span>
<span id="cb321-3"><a href="introduction-to-r.html#cb321-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span>  <span class="fu">data.frame</span>(gender,age)</span>
<span id="cb321-4"><a href="introduction-to-r.html#cb321-4" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span>  <span class="fu">na.omit</span>(df)</span></code></pre></div>
</div>
<div id="packages" class="section level3 unnumbered">
<h3>Packages</h3>
<p>A major advantage of R is that the basic software can be easily extended
by installing additional packages, of which more than 6,000 exist. You
can consult the R package directory to help find a package that has the
functions you need.<a href="#fn40" class="footnote-ref" id="fnref40"><sup>40</sup></a> RStudio has an interface for finding and
installing packages. See the Packages tab on RStudio’s lower-right
window.</p>
<p>Before running a script, you need to indicate which packages it needs,
beyond the default packages that are automatically loaded. The library
statement specifies that a package is required for execution. The
following example uses the measurements package to handle the conversion
of Fahrenheit to Celsius. The package’s documentation provides details
of how to use its various conversion options.</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="introduction-to-r.html#cb322-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(measurements) <span class="co"># previously installed</span></span>
<span id="cb322-2"><a href="introduction-to-r.html#cb322-2" aria-hidden="true" tabindex="-1"></a><span class="co"># convert F to C</span></span>
<span id="cb322-3"><a href="introduction-to-r.html#cb322-3" aria-hidden="true" tabindex="-1"></a><span class="fu">conv_unit</span>(<span class="dv">100</span>,<span class="st">&#39;F&#39;</span>,<span class="st">&#39;C&#39;</span>)</span></code></pre></div>
<pre><code>## [1] 37.77778</code></pre>
<blockquote>
<p>❓<strong>Skill builder</strong> Install the measurements package and run the
preceding code.</p>
</blockquote>
</div>
<div id="reading-a-file" class="section level3 unnumbered">
<h3>Reading a file</h3>
<p>Files are the usual form of input for R scripts. Fortunately, R can
handle a wide variety of input formats, including text (e.g., CSV),
statistical package (e.g., SAS), and XML. A common approach is to use a
spreadsheet to prepare a data file, export it as CSV, and then read it
into R.</p>
<p>Files can be read from the local computer on which R is installed or the
Internet, as the following sample code illustrates. We will use the
readr library for handling files, so you will need to install it before
running the following code.</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="introduction-to-r.html#cb324-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb324-2"><a href="introduction-to-r.html#cb324-2" aria-hidden="true" tabindex="-1"></a><span class="co"># read a local file (this will not work on your computer)</span></span>
<span id="cb324-3"><a href="introduction-to-r.html#cb324-3" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">&quot;Documents/R/Data/centralparktemps.txt&quot;</span>, <span class="at">delim=</span><span class="st">&quot;,&quot;</span>)</span></code></pre></div>
<p>You can also read a remote file using a URL.</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="introduction-to-r.html#cb325-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb325-2"><a href="introduction-to-r.html#cb325-2" aria-hidden="true" tabindex="-1"></a><span class="co"># read using a URL</span></span>
<span id="cb325-3"><a href="introduction-to-r.html#cb325-3" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;http://www.richardtwatson.com/data/centralparktemps.txt&#39;</span></span>
<span id="cb325-4"><a href="introduction-to-r.html#cb325-4" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(url, <span class="at">delim=</span><span class="st">&#39;,&#39;</span>)</span></code></pre></div>
<pre><code>## Rows: 1794 Columns: 3</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (3): year, month, temperature</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>You must define the separator for data fields with the delim keyword
(e.g., for a tab use <code>delim='t')</code>.</p>
<div id="learning-about-a-file" class="section level4 unnumbered">
<h4>Learning about a file</h4>
<p>After reading a file, you might want to learn about its contents. First,
you can click on the file’s name in the top-right window. This will open
the file in the top-left window. If it is a long file, only a portion,
such as the first 1000 rows, will be displayed. Second, you can execute
some R commands, as shown in the following code, to show the first few
and last few rows. You can also report the dimensions of the file, its
structure, and the type of object.</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="introduction-to-r.html#cb329-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb329-2"><a href="introduction-to-r.html#cb329-2" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;http://www.richardtwatson.com/data/centralparktemps.txt&#39;</span></span>
<span id="cb329-3"><a href="introduction-to-r.html#cb329-3" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(url, <span class="at">delim=</span><span class="st">&#39;,&#39;</span>)</span></code></pre></div>
<pre><code>## Rows: 1794 Columns: 3</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (3): year, month, temperature</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="introduction-to-r.html#cb333-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(t) <span class="co">#  first few rows</span></span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##    year month temperature
##   &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;
## 1  1869     1        35.1
## 2  1869    10        50.9
## 3  1869    11        40.3
## 4  1869    12        34.7
## 5  1869     2        34.5
## 6  1869     3        34.8</code></pre>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="introduction-to-r.html#cb335-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(t) <span class="co">#  last few rows</span></span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##    year month temperature
##   &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;
## 1  2018     1        31.7
## 2  2018     2        42  
## 3  2018     3        40.1
## 4  2018     4        49.5
## 5  2018     5        66.9
## 6  2018     6        71.7</code></pre>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="introduction-to-r.html#cb337-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(t) <span class="co"># dimension</span></span></code></pre></div>
<pre><code>## [1] 1794    3</code></pre>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="introduction-to-r.html#cb339-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(t) <span class="co"># structure of a dataset</span></span></code></pre></div>
<pre><code>## spec_tbl_df [1,794 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ year       : num [1:1794] 1869 1869 1869 1869 1869 ...
##  $ month      : num [1:1794] 1 10 11 12 2 3 4 5 6 7 ...
##  $ temperature: num [1:1794] 35.1 50.9 40.3 34.7 34.5 34.8 49.2 57.7 69.3 72.8 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   year = col_double(),
##   ..   month = col_double(),
##   ..   temperature = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="introduction-to-r.html#cb341-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(t) <span class="co">#type of object</span></span></code></pre></div>
<pre><code>## [1] &quot;spec_tbl_df&quot; &quot;tbl_df&quot;      &quot;tbl&quot;         &quot;data.frame&quot;</code></pre>
</div>
</div>
<div id="referencing-columns" class="section level3 unnumbered">
<h3>Referencing columns</h3>
<p>Columns within a table are referenced by using the format
tablename$columname. This is similar to the qualification method used
in SQL. The following code shows a few examples. It also illustrates how
to add a new column to an existing table.</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="introduction-to-r.html#cb343-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(measurements)</span>
<span id="cb343-2"><a href="introduction-to-r.html#cb343-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr) </span>
<span id="cb343-3"><a href="introduction-to-r.html#cb343-3" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;http://www.richardtwatson.com/data/centralparktemps.txt&#39;</span></span>
<span id="cb343-4"><a href="introduction-to-r.html#cb343-4" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(url, <span class="at">delim=</span><span class="st">&#39;,&#39;</span>)</span></code></pre></div>
<pre><code>## Rows: 1794 Columns: 3</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (3): year, month, temperature</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="introduction-to-r.html#cb347-1" aria-hidden="true" tabindex="-1"></a><span class="co"># qualify with table name to reference a column</span></span>
<span id="cb347-2"><a href="introduction-to-r.html#cb347-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(t<span class="sc">$</span>temperature)</span></code></pre></div>
<pre><code>## [1] 53.92246</code></pre>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="introduction-to-r.html#cb349-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(t<span class="sc">$</span>year)</span></code></pre></div>
<pre><code>## [1] 2018</code></pre>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="introduction-to-r.html#cb351-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(t<span class="sc">$</span>month)</span></code></pre></div>
<pre><code>## [1]  1 12</code></pre>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="introduction-to-r.html#cb353-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a new column with the temperature in Celsius</span></span>
<span id="cb353-2"><a href="introduction-to-r.html#cb353-2" aria-hidden="true" tabindex="-1"></a>t<span class="sc">$</span>Ctemp <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">conv_unit</span>(t<span class="sc">$</span>temperature,<span class="st">&#39;F&#39;</span>,<span class="st">&#39;C&#39;</span>),<span class="dv">1</span>) <span class="co"># round to one decimal</span></span></code></pre></div>
</div>
<div id="recoding" class="section level3 unnumbered">
<h3>Recoding</h3>
<p>Some analyses might be facilitated by the recoding of data. For
instance, you might want to split a continuous measure into two
categories. Imagine you decide to classify all temperatures greater than
or equal to 25ºC as ‘hot’ and the rest as ‘other.’ Here are the R
command to create a new column in table t called Category.</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="introduction-to-r.html#cb354-1" aria-hidden="true" tabindex="-1"></a>t<span class="sc">$</span>Category <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(t<span class="sc">$</span>Ctemp <span class="sc">&gt;=</span> <span class="dv">30</span>, <span class="st">&#39;Hot&#39;</span>,<span class="st">&#39;Other&#39;</span>)</span></code></pre></div>
</div>
<div id="deleting-a-column" class="section level3 unnumbered">
<h3>Deleting a column</h3>
<p>You can delete a column by setting each of its values to NULL.</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="introduction-to-r.html#cb355-1" aria-hidden="true" tabindex="-1"></a>t<span class="sc">$</span>Category <span class="ot">&lt;-</span>  <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="reshaping-data" class="section level3 unnumbered">
<h3>Reshaping data</h3>
<p>Data are not always in the shape that you want. For example, you might
have a spreadsheet that, for each year, lists the quarterly observations
(i.e., year and four quarterly values in one row). For analysis, you
typically need to have a row for each distinct observation (e.g., year,
quarter, value). <em>Gathering</em> converts a document from what is commonly
called <em>wide</em> to <em>narrow</em> format. It is akin to normalization in that
the new table has year and quarter as the identifier of each
observation.</p>
<p>Once the file has been read, you create appropriate column names for the
converted file using the colnames() function applied to the file t.
Thus, the input file has column names of Q1, Q2, etc, but it makes sense
for these to be integers in the new file in a new column called quarter.</p>
<p>The gather command specifies the file to be gathered, the column names
of the new file, and the columns of the input file to be gathered (i.e.,
the four quarters in columns 2 through 5). Note that you also need
convert the column quarter from character to integer.</p>
<p><em>Reshaping data with gathering and
spreading</em><img src="Figures/Chapter%2015/gather-spread.png" /></p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="introduction-to-r.html#cb356-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.5     ✓ dplyr   1.0.7
## ✓ tibble  3.1.6     ✓ stringr 1.4.0
## ✓ tidyr   1.1.4     ✓ forcats 0.5.1
## ✓ purrr   0.3.4</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="introduction-to-r.html#cb360-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;http://www.richardtwatson.com/data/gatherExample.csv&#39;</span></span>
<span id="cb360-2"><a href="introduction-to-r.html#cb360-2" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url)</span></code></pre></div>
<pre><code>## Rows: 2 Columns: 5</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (5): year, Q1, Q2, Q3, Q4</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="introduction-to-r.html#cb364-1" aria-hidden="true" tabindex="-1"></a>t</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##    year    Q1    Q2    Q3    Q4
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  2014     1     2     3     4
## 2  2015     5     6     7     8</code></pre>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="introduction-to-r.html#cb366-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(t) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;year&#39;</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)</span>
<span id="cb366-2"><a href="introduction-to-r.html#cb366-2" aria-hidden="true" tabindex="-1"></a>t</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##    year   `1`   `2`   `3`   `4`
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  2014     1     2     3     4
## 2  2015     5     6     7     8</code></pre>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="introduction-to-r.html#cb368-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gather with data in columns 2 through 5</span></span>
<span id="cb368-2"><a href="introduction-to-r.html#cb368-2" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">gather</span>(t,<span class="st">&#39;quarter&#39;</span>,<span class="st">&#39;value&#39;</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>) </span>
<span id="cb368-3"><a href="introduction-to-r.html#cb368-3" aria-hidden="true" tabindex="-1"></a>g<span class="sc">$</span>quarter <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(g<span class="sc">$</span>quarter)</span>
<span id="cb368-4"><a href="introduction-to-r.html#cb368-4" aria-hidden="true" tabindex="-1"></a>g</span></code></pre></div>
<pre><code>## # A tibble: 8 × 3
##    year quarter value
##   &lt;dbl&gt;   &lt;int&gt; &lt;dbl&gt;
## 1  2014       1     1
## 2  2015       1     5
## 3  2014       2     2
## 4  2015       2     6
## 5  2014       3     3
## 6  2015       3     7
## 7  2014       4     4
## 8  2015       4     8</code></pre>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="introduction-to-r.html#cb370-1" aria-hidden="true" tabindex="-1"></a><span class="co"># spread</span></span>
<span id="cb370-2"><a href="introduction-to-r.html#cb370-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">spread</span>(g,quarter,value)</span>
<span id="cb370-3"><a href="introduction-to-r.html#cb370-3" aria-hidden="true" tabindex="-1"></a>s</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##    year   `1`   `2`   `3`   `4`
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  2014     1     2     3     4
## 2  2015     5     6     7     8</code></pre>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="introduction-to-r.html#cb372-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(s) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;year&#39;</span>, <span class="st">&#39;Q1&#39;</span>,<span class="st">&#39;Q2&#39;</span>,<span class="st">&#39;Q3&#39;</span>,<span class="st">&#39;Q4&#39;</span>)</span>
<span id="cb372-2"><a href="introduction-to-r.html#cb372-2" aria-hidden="true" tabindex="-1"></a>s</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##    year    Q1    Q2    Q3    Q4
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  2014     1     2     3     4
## 2  2015     5     6     7     8</code></pre>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="introduction-to-r.html#cb374-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spreading takes a narrow file and converts it to wide or spreadsheet format. This is the reverse of gathering.</span></span>
<span id="cb374-2"><a href="introduction-to-r.html#cb374-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">spread</span>(g,quarter,value)</span>
<span id="cb374-3"><a href="introduction-to-r.html#cb374-3" aria-hidden="true" tabindex="-1"></a>s</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##    year   `1`   `2`   `3`   `4`
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  2014     1     2     3     4
## 2  2015     5     6     7     8</code></pre>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="introduction-to-r.html#cb376-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(s) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;year&#39;</span>, <span class="st">&#39;Q1&#39;</span>,<span class="st">&#39;Q2&#39;</span>,<span class="st">&#39;Q3&#39;</span>,<span class="st">&#39;Q4&#39;</span>)</span>
<span id="cb376-2"><a href="introduction-to-r.html#cb376-2" aria-hidden="true" tabindex="-1"></a>s</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##    year    Q1    Q2    Q3    Q4
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  2014     1     2     3     4
## 2  2015     5     6     7     8</code></pre>
</div>
<div id="writing-files" class="section level3 unnumbered">
<h3>Writing files</h3>
<p>R can write data in a few file formats. We just focus on text format in
this brief introduction. The following code illustrates how to create a
new column containing the temperature in C and renaming an existing
column. The revised table is then written as a csv text file to the
project’s folder.</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="introduction-to-r.html#cb378-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(measurements)</span>
<span id="cb378-2"><a href="introduction-to-r.html#cb378-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb378-3"><a href="introduction-to-r.html#cb378-3" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;http://www.richardtwatson.com/data/centralparktemps.txt&#39;</span></span>
<span id="cb378-4"><a href="introduction-to-r.html#cb378-4" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(url, <span class="at">delim=</span><span class="st">&#39;,&#39;</span>)</span></code></pre></div>
<pre><code>## Rows: 1794 Columns: 3</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (3): year, month, temperature</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="introduction-to-r.html#cb382-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute Celsius and round to one decimal place</span></span>
<span id="cb382-2"><a href="introduction-to-r.html#cb382-2" aria-hidden="true" tabindex="-1"></a>t<span class="sc">$</span>Ctemp <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">conv_unit</span>(t<span class="sc">$</span>temperature,<span class="st">&#39;F&#39;</span>,<span class="st">&#39;C&#39;</span>),<span class="dv">1</span>)</span>
<span id="cb382-3"><a href="introduction-to-r.html#cb382-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(t)[<span class="dv">3</span>] <span class="ot">&lt;-</span>  <span class="st">&#39;Ftemp&#39;</span> <span class="co"># rename third column to indicate Fahrenheit</span></span>
<span id="cb382-4"><a href="introduction-to-r.html#cb382-4" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(t,<span class="st">&quot;centralparktempsCF.txt&quot;</span>)</span></code></pre></div>
</div>
<div id="data-manipulation-with-dplyr" class="section level3 unnumbered">
<h3>Data manipulation with dplyr</h3>
<p>The dplyr package<a href="#fn41" class="footnote-ref" id="fnref41"><sup>41</sup></a> provides functions for efficiently
manipulating data sets. By providing a series of basic data handling
functions and use of the pipe function ( %&gt;% ),<a href="#fn42" class="footnote-ref" id="fnref42"><sup>42</sup></a> dplyr
implements a grammar for data manipulation. The pipe function is used to
pass data from one operation to the next.</p>
<p><em>Some dplyr functions</em></p>
<table>
<thead>
<tr class="header">
<th align="left">Function</th>
<th align="left">Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">filter()</td>
<td align="left">Select rows</td>
</tr>
<tr class="even">
<td align="left">select()</td>
<td align="left">Select columns</td>
</tr>
<tr class="odd">
<td align="left">arrange()</td>
<td align="left">Sort rows</td>
</tr>
<tr class="even">
<td align="left">summarize()</td>
<td align="left">Compute a single summary statistic</td>
</tr>
<tr class="odd">
<td align="left">group_by()</td>
<td align="left">Pair with summarize() to analyze groups within a dataset</td>
</tr>
<tr class="even">
<td align="left">inner_join()</td>
<td align="left">Join two tables</td>
</tr>
<tr class="odd">
<td align="left">mutate()</td>
<td align="left">Create a new column</td>
</tr>
</tbody>
</table>
<p>Here are some examples using dplyr with data frame t.</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="introduction-to-r.html#cb383-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb383-2"><a href="introduction-to-r.html#cb383-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb383-3"><a href="introduction-to-r.html#cb383-3" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;http://www.richardtwatson.com/data/centralparktemps.txt&#39;</span></span>
<span id="cb383-4"><a href="introduction-to-r.html#cb383-4" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(url, <span class="at">delim=</span><span class="st">&#39;,&#39;</span>)</span></code></pre></div>
<pre><code>## Rows: 1794 Columns: 3</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (3): year, month, temperature</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="introduction-to-r.html#cb387-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a row subset</span></span>
<span id="cb387-2"><a href="introduction-to-r.html#cb387-2" aria-hidden="true" tabindex="-1"></a>trow <span class="ot">&lt;-</span>  <span class="fu">filter</span>(t, year <span class="sc">==</span> <span class="dv">1999</span>)</span>
<span id="cb387-3"><a href="introduction-to-r.html#cb387-3" aria-hidden="true" tabindex="-1"></a><span class="co"># a column subset</span></span>
<span id="cb387-4"><a href="introduction-to-r.html#cb387-4" aria-hidden="true" tabindex="-1"></a>tcol <span class="ot">&lt;-</span>  <span class="fu">select</span>(t, year)</span></code></pre></div>
<p>The following example illustrates application of the pipe function. The
data frame t is piped to select(), and the results of select method
passed onto filter(). The final output is stored in trowcol, which
contains year, month, and Celsius temperature for the years 1990 through
1999.</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="introduction-to-r.html#cb388-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a combo subset and use of the pipe function</span></span>
<span id="cb388-2"><a href="introduction-to-r.html#cb388-2" aria-hidden="true" tabindex="-1"></a>trowcol <span class="ot">&lt;-</span>  t <span class="sc">%&gt;%</span> <span class="fu">select</span>(year, month, temperature) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year <span class="sc">&gt;</span> <span class="dv">1989</span> <span class="sc">&amp;</span> year <span class="sc">&lt;</span> <span class="dv">2000</span>)</span></code></pre></div>
</div>
<div id="sorting" class="section level3 unnumbered">
<h3>Sorting</h3>
<p>You can also use dplyr for sorting.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="introduction-to-r.html#cb389-1" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span>  <span class="fu">arrange</span>(t, <span class="fu">desc</span>(year),month)</span></code></pre></div>
<blockquote>
<p>❓<strong>Skill builder</strong></p>
<ul>
<li><p>View the <u>web page</u> of yearly CO<sub>2</sub> emissions (million metric
tons) since the beginning of the industrial revolution.</p></li>
<li><p>Create a new text file using R</p></li>
<li><p>Clean up the file for use with R and save it as CO2.txt</p></li>
<li><p>Import (Import Dataset) the file into R</p></li>
<li><p>Plot year versus CO<sub>2</sub> emissions</p></li>
</ul>
</blockquote>
</div>
<div id="summarizing-data" class="section level3 unnumbered">
<h3>Summarizing data</h3>
<p>The dplyr function can be used for summarizing data in a specified way
(e.g., mean, minimum, standard deviation). In the sample code, a file
containing the mean temperature for each year is created. Notice the use
of the pipe function to first group the data by year and then compute
the mean for each group.</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb390-1"><a href="introduction-to-r.html#cb390-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb390-2"><a href="introduction-to-r.html#cb390-2" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">&#39;http://www.richardtwatson.com/data/centralparktemps.txt&#39;</span></span>
<span id="cb390-3"><a href="introduction-to-r.html#cb390-3" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(url, <span class="at">delim=</span><span class="st">&#39;,&#39;</span>)</span></code></pre></div>
<pre><code>## Rows: 1794 Columns: 3</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (3): year, month, temperature</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="introduction-to-r.html#cb394-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span>  t  <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">averageF =</span> <span class="fu">mean</span>(temperature))</span></code></pre></div>
</div>
<div id="adding-a-column" class="section level3 unnumbered">
<h3>Adding a column</h3>
<p>The following example shows how to add a column and compute its average.</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="introduction-to-r.html#cb395-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add column</span></span>
<span id="cb395-2"><a href="introduction-to-r.html#cb395-2" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span>  <span class="fu">mutate</span>(t, <span class="at">CTemp =</span> (temperature<span class="dv">-32</span>)<span class="sc">*</span><span class="dv">5</span><span class="sc">/</span><span class="dv">9</span>)</span>
<span id="cb395-3"><a href="introduction-to-r.html#cb395-3" aria-hidden="true" tabindex="-1"></a><span class="co"># summarize</span></span>
<span id="cb395-4"><a href="introduction-to-r.html#cb395-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(t, <span class="fu">mean</span>(CTemp))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   `mean(CTemp)`
##           &lt;dbl&gt;
## 1          12.2</code></pre>
<blockquote>
<p>❓<strong>Skill builder</strong> Create a file with the maximum temperature for each
year.</p>
</blockquote>
</div>
<div id="merging-files" class="section level3 unnumbered">
<h3>Merging files</h3>
<p>If there is a common column in two files, then they can be merged using
dplyr.::inner_join().<a href="#fn43" class="footnote-ref" id="fnref43"><sup>43</sup></a> This is the same as joining two tables
using a primary key and foreign key match. In the following code, a file
is created with the mean temperature for each year, and it is merged
with CO<sub>2</sub> readings for the same set of years.</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="introduction-to-r.html#cb397-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb397-2"><a href="introduction-to-r.html#cb397-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb397-3"><a href="introduction-to-r.html#cb397-3" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;http://www.richardtwatson.com/data/centralparktemps.txt&#39;</span></span>
<span id="cb397-4"><a href="introduction-to-r.html#cb397-4" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(url, <span class="at">delim=</span><span class="st">&#39;,&#39;</span>)</span></code></pre></div>
<pre><code>## Rows: 1794 Columns: 3</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (3): year, month, temperature</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="introduction-to-r.html#cb401-1" aria-hidden="true" tabindex="-1"></a><span class="co"># average monthly temp for each year</span></span>
<span id="cb401-2"><a href="introduction-to-r.html#cb401-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span>  t <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(temperature))</span>
<span id="cb401-3"><a href="introduction-to-r.html#cb401-3" aria-hidden="true" tabindex="-1"></a><span class="co"># read yearly carbon data (source: http://co2now.org/Current-CO2/CO2-Now/noaa-mauna-loa-co2-data.html)</span></span>
<span id="cb401-4"><a href="introduction-to-r.html#cb401-4" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;http://www.richardtwatson.com/data/carbon1959-2011.txt&#39;</span></span>
<span id="cb401-5"><a href="introduction-to-r.html#cb401-5" aria-hidden="true" tabindex="-1"></a>carbon <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(url,  <span class="at">delim=</span><span class="st">&#39;,&#39;</span>) </span></code></pre></div>
<pre><code>## Rows: 53 Columns: 2</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (2): year, CO2</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="introduction-to-r.html#cb405-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span>  <span class="fu">inner_join</span>(a,carbon)</span></code></pre></div>
<pre><code>## Joining, by = &quot;year&quot;</code></pre>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="introduction-to-r.html#cb407-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(m)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##    year  mean   CO2
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  1959  55.4  316.
## 2  1960  54.0  317.
## 3  1961  55.0  318.
## 4  1962  53.4  318.
## 5  1963  53.6  319.
## 6  1964  54.6  320.</code></pre>
</div>
<div id="data-manipulation-with-sqldf" class="section level3 unnumbered">
<h3>Data manipulation with sqldf</h3>
<p>The sqldf package enables use of the broad power of SQL to extract rows
or columns from a data frame to meet the needs of a particular analysis.
It provides essentially the same data manipulation capabilities as
dplyr. The following example illustrates use of sqldf.</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="introduction-to-r.html#cb409-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sqldf)</span></code></pre></div>
<pre><code>## Loading required package: gsubfn</code></pre>
<pre><code>## Loading required package: proto</code></pre>
<pre><code>## Warning in doTryCatch(return(expr), name, parentenv, handler): unable to load shared object &#39;/Library/Frameworks/R.framework/Resources/modules//R_X11.so&#39;:
##   dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 0x0006): Library not loaded: /opt/X11/lib/libSM.6.dylib
##   Referenced from: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/modules/R_X11.so
##   Reason: tried: &#39;/opt/X11/lib/libSM.6.dylib&#39; (no such file), &#39;/Library/Frameworks/R.framework/Resources/lib/libSM.6.dylib&#39; (no such file), &#39;/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libSM.6.dylib&#39; (no such file)</code></pre>
<pre><code>## Warning in system2(&quot;/usr/bin/otool&quot;, c(&quot;-L&quot;, shQuote(DSO)), stdout
## = TRUE): running command &#39;&#39;/usr/bin/otool&#39; -L &#39;/var/folders/
## m3/0wz4s80d4l595_111vshn2r40000gp/T//RtmpBDZj1C/renv-system-library/tcltk/libs//
## tcltk.so&#39;&#39; had status 1</code></pre>
<pre><code>## Could not load tcltk.  Will use slower R code instead.</code></pre>
<pre><code>## Loading required package: RSQLite</code></pre>
<pre><code>## 
## Attaching package: &#39;RSQLite&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:RMySQL&#39;:
## 
##     isIdCurrent</code></pre>
<pre><code>## sqldf will default to using MySQL</code></pre>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="introduction-to-r.html#cb419-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb419-2"><a href="introduction-to-r.html#cb419-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">sqldf.driver =</span> <span class="st">&quot;SQLite&quot;</span>) <span class="co"># to avoid a conflict with RMySQL</span></span>
<span id="cb419-3"><a href="introduction-to-r.html#cb419-3" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;http://www.richardtwatson.com/data/centralparktemps.txt&#39;</span></span>
<span id="cb419-4"><a href="introduction-to-r.html#cb419-4" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(url, <span class="at">delim=</span><span class="st">&#39;,&#39;</span>)</span></code></pre></div>
<pre><code>## Rows: 1794 Columns: 3</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (3): year, month, temperature</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="introduction-to-r.html#cb423-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a row subset</span></span>
<span id="cb423-2"><a href="introduction-to-r.html#cb423-2" aria-hidden="true" tabindex="-1"></a>trowcol <span class="ot">&lt;-</span>  <span class="fu">sqldf</span>(<span class="st">&quot;select year, month, temperature from t where year &gt; 1989 and year &lt; 2000&quot;</span>)</span></code></pre></div>
<p>However, sqldf does not enable you to embed R functions within an SQL
command. For this reason, dplyr is the recommended approach for data
manipulation. However, there might be occasions when you find it more
efficient to first execute a complex query in SQL and then do further
analysis with dplyr.</p>
</div>
<div id="correlation-coefficient" class="section level3 unnumbered">
<h3>Correlation coefficient</h3>
<p>A correlation coefficient is a measure of the covariation between two
sets of observations. In this case, we are interested in whether there
is a statistically significant covariation between temperature and the
level of atmospheric CO<sub>2</sub>.<a href="#fn44" class="footnote-ref" id="fnref44"><sup>44</sup></a></p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="introduction-to-r.html#cb424-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(m<span class="sc">$</span>mean, m<span class="sc">$</span>CO2)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  m$mean and m$CO2
## t = 3.1173, df = 51, p-value = 0.002997
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.1454994 0.6049393
## sample estimates:
##       cor 
## 0.4000598</code></pre>
<p>The following results indicate that a correlation of .40 is a
statistically significant as the p-value is less than 0.05, the common
threshold for significance testing. Thus, we conclude that, because
there is a small chance (p = .002997) of observing by chance such a
value for the correlation coefficient, there is a relationship between
mean temperature and the level of atmospheric CO<sub>2</sub>. Given that global
warming theory predicts an increase in temperature with an increase in
atmospheric CO<sub>2</sub>, we can also state that the observations support this
theory. In other words, an increase in CO<sub>2</sub> increases temperatures in
Central Park.</p>
<table style="width:58%;">
<colgroup>
<col width="58%" />
</colgroup>
<tbody>
<tr class="odd">
<td><p><strong><em>Pearson’s product-moment
correlation</em></strong></p>
<p>data: m<span class="math inline">\(mean and m\)</span>CO2</p>
<p>t = 3.1173, df = 51, p-value = 0.002997</p>
<p>95 percent confidence interval:</p>
<p>0.1454994 0.6049393</p>
<p>sample estimates:</p>
<p>cor</p>
<p>0.4000598</p></td>
</tr>
</tbody>
</table>
<p>When reporting correlation coefficients, you can you use the terms
small, moderate, and large in accordance with the values specified in
following table.</p>
<table>
<thead>
<tr class="header">
<th align="left">Correlation coefficient</th>
<th align="left">Effect size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">.10 - .30</td>
<td align="left">Small</td>
</tr>
<tr class="even">
<td align="left">.30 - .50</td>
<td align="left">Moderate</td>
</tr>
<tr class="odd">
<td align="left">&gt; .50</td>
<td align="left">Large</td>
</tr>
</tbody>
</table>
<p>If we want to understand the nature of the relationship, we could fit a
linear model.</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="introduction-to-r.html#cb426-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(m<span class="sc">$</span>mean <span class="sc">~</span> m<span class="sc">$</span>CO2)</span>
<span id="cb426-2"><a href="introduction-to-r.html#cb426-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = m$mean ~ m$CO2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1260 -0.7227  0.1217  0.6490  2.1189 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 48.291319   2.149937  22.462   &lt;2e-16 ***
## m$CO2        0.019208   0.006162   3.117    0.003 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.016 on 51 degrees of freedom
## Multiple R-squared:   0.16,  Adjusted R-squared:  0.1436 
## F-statistic: 9.718 on 1 and 51 DF,  p-value: 0.002997</code></pre>
<p>The following results indicate a linear model is significant (p &lt; .05),
and it explains 14.36% (adjusted multiple R-squared) of the variation
between temperature and atmospheric CO<sub>2</sub>. The linear equation is</p>
<p><span class="math display">\[temperature = 48.29 + 0.019208* CO2\]</span></p>
<p>As CO<sub>2</sub> emissions are measured in parts per millions (ppm), an increase
of 1.0 ppm predicts an annual mean temperature increase in Central Park
of .01920 F°. Currently CO<sub>2</sub> emissions are increasing at about 2.0 ppm
per year.</p>
<p>As a linear model explains about 14% of the variation, this suggests
that there might other variables that should be considered (e.g., level
of volcanic activity) and that the relationship might not be linear.</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>timestamp</th>
<th>airTemp</th>
<th>humidity</th>
<th>p recipitation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2010-01-01 03:00:00</td>
<td>44</td>
<td>93</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>2010-01-01 04:00:00</td>
<td>44</td>
<td>89</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>2010-01-01 05:00:00</td>
<td>43</td>
<td>89</td>
<td>0</td>
</tr>
<tr class="even">
<td>4</td>
<td>2010-01-01 06:00:00</td>
<td>42</td>
<td>83</td>
<td>0</td>
</tr>
<tr class="odd">
<td>5</td>
<td>2010-01-01 07:00:00</td>
<td>41</td>
<td>86</td>
<td>0</td>
</tr>
<tr class="even">
<td>6</td>
<td>2010-01-01 08:00:00</td>
<td>40</td>
<td>79</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="database-access" class="section level2 unnumbered">
<h2>Database access</h2>
<p>The DBI package provides a convenient way for a direct connection
between R and a relational database, such as MySQL or PostgreSQL. Once
the connection has been made, you can run an SQL query and load the
results into a R data frame.</p>
<p>The dbConnect() function makes the connection. You specify the type of
relational database, url, database name, userid, and password, as shown
in the following code.<a href="#fn45" class="footnote-ref" id="fnref45"><sup>45</sup></a></p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="introduction-to-r.html#cb428-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DBI)</span>
<span id="cb428-2"><a href="introduction-to-r.html#cb428-2" aria-hidden="true" tabindex="-1"></a>conn <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RMySQL<span class="sc">::</span><span class="fu">MySQL</span>(), <span class="st">&quot;www.richardtwatson.com&quot;</span>, <span class="at">dbname=</span><span class="st">&quot;Weather&quot;</span>, <span class="at">user=</span><span class="st">&quot;student&quot;</span>, <span class="at">password=</span><span class="st">&quot;student&quot;</span>)</span>
<span id="cb428-3"><a href="introduction-to-r.html#cb428-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Query the database and create file t for use with R</span></span>
<span id="cb428-4"><a href="introduction-to-r.html#cb428-4" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(conn,<span class="st">&quot;select * from record;&quot;</span>)</span>
<span id="cb428-5"><a href="introduction-to-r.html#cb428-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(t)</span></code></pre></div>
<pre><code>##             Timestamp Temperature
## 1 2010-01-01 01:00:00          44
## 2 2010-01-01 02:00:00          44
## 3 2010-01-01 03:00:00          44
## 4 2010-01-01 04:00:00          44
## 5 2010-01-01 05:00:00          43
## 6 2010-01-01 06:00:00          42</code></pre>
<p>For security reasons, it is not a good idea to put database access
details in your R code. They should be hidden in a file. I recommend
that you create a csv file within your R code folder to containing
database access parameters. First, create a new directory or folder
(File &gt; New Project &gt; New Directory &gt; Empty Project), called dbaccess
for containing you database access files. Then, create a csvfile (Use
File &gt; New File &gt; Text File) with the name weather_richardtwatson.csv
in the newly created folder containing the following data:</p>
<p><em>url,dbname,user,password:</em></p>
<p><em>richardtwatson.com,Weather,student,student</em></p>
<p>The R code will now be:</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="introduction-to-r.html#cb430-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Database access</span></span>
<span id="cb430-2"><a href="introduction-to-r.html#cb430-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb430-3"><a href="introduction-to-r.html#cb430-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DBI)</span>
<span id="cb430-4"><a href="introduction-to-r.html#cb430-4" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;dbaccess/weather_richardtwatson.csv&#39;</span></span>
<span id="cb430-5"><a href="introduction-to-r.html#cb430-5" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span>  <span class="fu">read_csv</span>(url)</span>
<span id="cb430-6"><a href="introduction-to-r.html#cb430-6" aria-hidden="true" tabindex="-1"></a>conn <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RMySQL<span class="sc">::</span><span class="fu">MySQL</span>(), d<span class="sc">$</span>url, <span class="at">dbname=</span>d<span class="sc">$</span>dbname, <span class="at">user=</span>d<span class="sc">$</span>user, <span class="at">password=</span>d<span class="sc">$</span>password)</span>
<span id="cb430-7"><a href="introduction-to-r.html#cb430-7" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(conn,<span class="st">&quot;SELECT timestamp, airTemp from record;&quot;</span>)</span>
<span id="cb430-8"><a href="introduction-to-r.html#cb430-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(t)</span></code></pre></div>
<p>Despite the prior example, I will continue to show database access
parameters because you need them to run the sample code. However, in
practice you should follow the security advice given.</p>
</div>
<div id="timestamps" class="section level2 unnumbered">
<h2>Timestamps</h2>
<p>Many data sets include a timestamp to indicate when an observation was
recorded. A timestamp will show the data and time to the second or
microsecond. The format of a standard timestamp is yyyy-mm-dd hh:mm:ss
(e.g., 2010-01-31 03:05:46).</p>
<p>Some R functions, including those in the lubridate package, can detect a
standard format timestamp and support operations for extracting parts of
it, such as the year, month, day, hour, and so forth. The following
example shows how to use lubridate to extract the month and year from a
character string in standard timestamp format.</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="introduction-to-r.html#cb431-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb431-2"><a href="introduction-to-r.html#cb431-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DBI)</span>
<span id="cb431-3"><a href="introduction-to-r.html#cb431-3" aria-hidden="true" tabindex="-1"></a>conn <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RMySQL<span class="sc">::</span><span class="fu">MySQL</span>(), <span class="st">&quot;www.richardtwatson.com&quot;</span>, <span class="at">dbname=</span><span class="st">&quot;Weather&quot;</span>, <span class="at">user=</span><span class="st">&quot;student&quot;</span>, <span class="at">password=</span><span class="st">&quot;student&quot;</span>)</span>
<span id="cb431-4"><a href="introduction-to-r.html#cb431-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Query the database and create file t for use with R</span></span>
<span id="cb431-5"><a href="introduction-to-r.html#cb431-5" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(conn,<span class="st">&quot;select * from record;&quot;</span>)</span>
<span id="cb431-6"><a href="introduction-to-r.html#cb431-6" aria-hidden="true" tabindex="-1"></a>t<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">year</span>(t<span class="sc">$</span>timestamp)</span>
<span id="cb431-7"><a href="introduction-to-r.html#cb431-7" aria-hidden="true" tabindex="-1"></a>t<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">month</span>(t<span class="sc">$</span>timestamp)</span>
<span id="cb431-8"><a href="introduction-to-r.html#cb431-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(t)</span></code></pre></div>
</div>
<div id="excel-files" class="section level2 unnumbered">
<h2>Excel files</h2>
<p>There are a number of packages with methods for reading an Excel file.
Of these, readxl seems to be the simplest. However, it can handle only
files stored locally, which is the case with most of the packages
examined. If the required Excel spreadsheet is stored remotely, then
download it and store lit ocally.</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="introduction-to-r.html#cb432-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb432-2"><a href="introduction-to-r.html#cb432-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb432-3"><a href="introduction-to-r.html#cb432-3" aria-hidden="true" tabindex="-1"></a><span class="co"># read remote file and store on disk</span></span>
<span id="cb432-4"><a href="introduction-to-r.html#cb432-4" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span>  <span class="st">&#39;http://www.richardtwatson.com/data/GDP.xlsx&#39;</span></span>
<span id="cb432-5"><a href="introduction-to-r.html#cb432-5" aria-hidden="true" tabindex="-1"></a><span class="fu">GET</span>(url,<span class="fu">write_disk</span>(<span class="st">&#39;temp.xlsx&#39;</span>,<span class="at">overwrite =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## Response [https://www.richardtwatson.com/data/GDP.xlsx]
##   Date: 2021-12-26 18:44
##   Status: 200
##   Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
##   Size: 888 kB
## &lt;ON DISK&gt;  /Users/rickwatson/Dropbox/R/DataManagement/temp.xlsx</code></pre>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="introduction-to-r.html#cb434-1" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span>  <span class="fu">read_excel</span>(<span class="st">&#39;temp.xlsx&#39;</span>,<span class="at">sheet =</span> <span class="dv">1</span>,<span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="r-resources" class="section level2 unnumbered">
<h2>R resources</h2>
<p>The vast number of packages makes the learning of R a major challenge.
The basics can be mastered quite quickly, but you will soon find that
many problems require special features or the data need some
manipulation. Once you learn how to solve a particular problem, make
certain you save the script, with some embedded comments, so you can
reuse the code for a future problem. There are books that you might find
useful to have in electronic format on your computer or tablet, and one
of these is listed at the end of the chapter. There are, however, many
more books,<a href="#fn46" class="footnote-ref" id="fnref46"><sup>46</sup></a> both of a general and specialized nature. The
<a href="http://cran.r-project.org/doc/contrib/Short-refcard.pdf"><u><em>R Reference
Card</em></u></a> is
handy to keep nearby when you are writing scripts. I printed and
laminated a copy, and it’s in the top drawer of my desk. A useful
website is <a href="http://www.statmethods.net"><u>Quick-R</u></a>, which is an
online reference for common tasks, such as those covered in this
chapter. For a quick tutorial, you can <a href="http://tryr.codeschool.com"><u>Try
R</u></a>.</p>
</div>
<div id="r-and-data-analytics" class="section level2 unnumbered">
<h2>R and data analytics</h2>
<p>R is a platform for a wide variety of data analytics, including</p>
<ul>
<li><p>Statistical analysis</p></li>
<li><p>Data visualization</p></li>
<li><p>HDFS and cluster computing</p></li>
<li><p>Text mining</p></li>
<li><p>Energy Informatics</p></li>
<li><p>Dashboards</p></li>
</ul>
<p>You have probably already completed an introductory statistical analysis
course, and you can now use R for all your statistical needs. In
subsequent chapters, we will discuss data visualization, HDFS and
cluster computing, and text mining. <a href="http://energyinformatics.info"><u>Energy
Informatics</u></a> is concerned with
optimizing energy flows, and R is an appropriate tool for analysis and
optimization of energy systems. R is being used extensively to analyze
climate change data.<a href="#fn47" class="footnote-ref" id="fnref47"><sup>47</sup></a></p>
<p>R is also a programming language. You might find that in some
situations, R provides a quick method for reshaping files and performing
calculations.</p>
</div>
<div id="summary-15" class="section level2 unnumbered">
<h2>Summary</h2>
<p>R is a free software environment for statistical computing, data
visualization, and data analytics. RStudio is a commonly used integrated
development environment (IDE) for R. A script is a set of R commands.
Store all R scripts and data for a project in the same folder or
directory. An R dataset is a table that can be stored as a vector,
matrix, array, data frame, and list. In R, an object is anything that
can be assigned to a variable. R can handle the four types of data:
nominal, ordinal, interval, and ratio. Nominal and ordinal data types
are also known as factors. Defining a column as a factor determines how
its data are analyzed and presented. Missing values are indicated by NA.
R can handle a wide variety of input formats, including text (e.g.,
CSV), statistical package (e.g., SAS), and XML. Data can be reshaped.
Gathering converts a document from what is commonly called wide to
narrow format. Spreading takes a narrow file and converts it to wide
format. Columns within a table are referenced using the format
tablename$columname. R can write data to a file. A major advantage of R
is that the basic software can be easily extended by installing
additional packages. The dplyr packages adds functionality for data
management and reporting. Learning R is a major challenge because of the
many packages available.</p>
</div>
<div id="key-terms-and-concepts-12" class="section level2 unnumbered">
<h2>Key terms and concepts</h2>
<table>
<tbody>
<tr class="odd">
<td align="left">Aggregate</td>
<td align="left">R</td>
</tr>
<tr class="even">
<td align="left">Array</td>
<td align="left">Reshape</td>
</tr>
<tr class="odd">
<td align="left">Data frame</td>
<td align="left">Script</td>
</tr>
<tr class="even">
<td align="left">Data type</td>
<td align="left">Spread</td>
</tr>
<tr class="odd">
<td align="left">Factor</td>
<td align="left">SQL</td>
</tr>
<tr class="even">
<td align="left">Gather</td>
<td align="left">Tibble</td>
</tr>
<tr class="odd">
<td align="left">List</td>
<td align="left">Subset</td>
</tr>
<tr class="even">
<td align="left">Matrix</td>
<td align="left">Vector</td>
</tr>
<tr class="odd">
<td align="left">Package</td>
<td align="left"></td>
</tr>
</tbody>
</table>
</div>
<div id="references" class="section level2 unnumbered">
<h2>References</h2>
<p>Wickham, H., &amp; Grolemund, G. (2017). R for data science: O’Reilly.</p>
</div>
<div id="exercises-14" class="section level2 unnumbered">
<h2>Exercises</h2>
<ol style="list-style-type: decimal">
<li><p>Access
<a href="http://richardtwatson.com/data/manheim.txt"><u>richardtwatson.com/data/manheim.txt</u></a>
which contains details of the sales of three car models: X, Y,
and Z.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Use the table function to compute the number of sales for each
type of model.</p></li>
<li><p>Use the table function to compute the number of sales for each
type of sale.</p></li>
<li><p>Report the mean price for each model.</p></li>
<li><p>Report the mean price for each type of sale.</p></li>
</ol></li>
<li><p>Use the ‘Import Dataset’ feature of RStudio to read
<a href="http://www.richardtwatson.com/data/electricityprices.csv" class="uri">http://www.richardtwatson.com/data/electricityprices.csv</a>, which
contains details of electricity prices for a major city.<a href="#fn48" class="footnote-ref" id="fnref48"><sup>48</sup></a></p>
<ol style="list-style-type: lower-alpha">
<li><p>What is the maximum cost?</p></li>
<li><p>What is the minimum cost?</p></li>
<li><p>What is the mean cost?</p></li>
<li><p>What is the median cost?</p></li>
</ol></li>
<li><p>Read the table
<a href="http://richardtwatson.com/data/wealth.csv"><u>richardtwatson.com/data/wealth.csv</u></a>
containing details of the wealth of various countries and complete
the following exercises.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Sort the table by GDP per capita.</p></li>
<li><p>What is the average GDP per capita?</p></li>
<li><p>Compute the ratio of US GDP per capita to the average GDP per
capita.</p></li>
<li><p>What’s the correlation between GDP per capita and wealth per
capita?</p></li>
</ol></li>
<li><p>Merge the data for weather (database weather at richardtwatson.com
discussed in the chapter) and electricity prices (Use RStudio’s
‘Import Dataset’ to read
<a href="http://www.richardtwatson.com/data/electricityprices.csv" class="uri">http://www.richardtwatson.com/data/electricityprices.csv</a>) and
compute the correlation between temperature and electricity price.
<strong>Hint</strong>: MySQL might return a timestamp with decimal seconds (e.g.,
2010-01-01 01:00:00.0), and you can remove the rightmost two
characters using substr(),<a href="#fn49" class="footnote-ref" id="fnref49"><sup>49</sup></a> so that the two timestamp
columns are of the same format and length. Also, you need to ensure
that the timestamps from the two data frames are of the same data
type (e.g., both character).</p></li>
<li><p>Get the list of failed US banks from
<a href="https://explore.data.gov/Banking-Finance-and-Insurance/FDIC-Failed-Bank-List/pwaj-zn2n"><u>https://explore.data.gov/Banking-Finance-and-Insurance/FDIC-Failed-Bank-List/pwaj-zn2n</u></a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Determine how many banks failed in each state.</p></li>
<li><p>How many banks were not acquired (hint: nrow() will count rows
in a table)?</p></li>
<li><p>How many banks were closed each year (hint: use strptime() and
the lubridate package)?</p></li>
</ol></li>
<li><p>Use Table01 of U.S. broccoli data on farms and area harvested from
<a href="http://usda.mannlib.cornell.edu/MannUsda/viewDocumentInfo.do?documentID=1816"><u>http://usda.mannlib.cornell.edu/MannUsda/viewDocumentInfo.do?documentID=1816</u></a>.
Get rid of unwanted rows to create a spreadsheet for the area
harvested with one header row and the 50 states. Change cells
without integer values to 0 and save the file in CSV format for
reading with R.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Reshape the data so that each observation contains state name,
year, and area harvested.</p></li>
<li><p>Add hectares as a column in the table. Round the calculation to
two decimal places.</p></li>
<li><p>Compute total hectares harvested each year for which data are
available.</p></li>
<li><p>Save the reshaped file.</p></li>
</ol></li>
</ol>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="39">
<li id="fn39"><p>RStudio provides a keyboard command, which is Alt+-
(Windows &amp; Linux) or Option+- (Mac)<a href="introduction-to-r.html#fnref39" class="footnote-back">↩︎</a></p></li>
<li id="fn40"><p><a href="http://cran.r-project.org/web/packages/" class="uri">http://cran.r-project.org/web/packages/</a><a href="introduction-to-r.html#fnref40" class="footnote-back">↩︎</a></p></li>
<li id="fn41"><p><a href="http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html" class="uri">http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html</a><a href="introduction-to-r.html#fnref41" class="footnote-back">↩︎</a></p></li>
<li id="fn42"><p>Short cuts is Ctrl+Shift+M (Windows &amp; Linux) and
Cmd+Shift+M (Mac)<a href="introduction-to-r.html#fnref42" class="footnote-back">↩︎</a></p></li>
<li id="fn43"><p>This is the R notation for indicating the package (dplyr)
to which a method (inner_join) belongs.<a href="introduction-to-r.html#fnref43" class="footnote-back">↩︎</a></p></li>
<li id="fn44"><p>As I continually revise data files to include the latest
observations, your answer might differ for this and other analyses.<a href="introduction-to-r.html#fnref44" class="footnote-back">↩︎</a></p></li>
<li id="fn45"><p>You will likely get a warning message of the form
“unrecognized MySQL field type 7 in column 0 imported as character,”
because R does does recognize the first column as a timestamp. You
can ignore it, but later you might need to convert the column to R’s
timestamp format.<a href="introduction-to-r.html#fnref45" class="footnote-back">↩︎</a></p></li>
<li id="fn46"><p><a href="http://www.r-project.org/doc/bib/R-books.html" class="uri">http://www.r-project.org/doc/bib/R-books.html</a><a href="introduction-to-r.html#fnref46" class="footnote-back">↩︎</a></p></li>
<li id="fn47"><p><a href="http://chartsgraphs.wordpress.com/category/r-climate-data-analysis-tool/" class="uri">http://chartsgraphs.wordpress.com/category/r-climate-data-analysis-tool/</a><a href="introduction-to-r.html#fnref47" class="footnote-back">↩︎</a></p></li>
<li id="fn48"><p>Note these prices have been transformed from the original
values, but are still representative of the changes over time.<a href="introduction-to-r.html#fnref48" class="footnote-back">↩︎</a></p></li>
<li id="fn49"><p><a href="http://www.statmethods.net/management/functions.html" class="uri">http://www.statmethods.net/management/functions.html</a><a href="introduction-to-r.html#fnref49" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="organizational-intelligence.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-visualization-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["DataManagement.pdf", "DataManagement.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
